package shared

import (
	"dlt-ingress/src/main/config"
	"fmt"
	"strings"

	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/event"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/port/retry"
)

// RegistrableListener is implemented by every event listener so the registry
// can register it uniformly. EventType, Name, and AsListener are generated by genlistener
// — see <name>_listener_gen.go.
type RegistrableListener interface {
	EventType() string
	Name() string
	AsListener() event.Listener
}

type ListenerRegistrar struct {
	registry       *event.ListenerRegistry
	retryer        retry.Retryer
	bcConfig       *config.BcRetryableListenerConfig
	listenerConfig *config.BcListenerConfig
}

func NewListenerRegistrar(
	registry *event.ListenerRegistry,
	retryer retry.Retryer,
	bcConfig *config.BcRetryableListenerConfig,
	listenerConfig *config.BcListenerConfig,
) *ListenerRegistrar {
	return &ListenerRegistrar{registry, retryer, bcConfig, listenerConfig}
}

func (r *ListenerRegistrar) RegisterRetryable(l RegistrableListener) {
	if strings.HasPrefix(l.Name(), "order") {
		panic(fmt.Errorf("the %s should be registered using RegisterOrder. Please use it instead", l.Name()))
	}
	r.registry.Register(
		l.EventType(),
		event.NewListenerDefinition(
			l.Name(),
			WrapRetryableListener(l.AsListener(), r.retryer, r.bcConfig),
			event.WithConcurrencyLimit(GetListenerConcurrency(l.Name(), r.listenerConfig)),
			event.WithExecutionTimeout(GetListenerExecutionTimeout(l.Name(), r.listenerConfig)),
		),
	)
}

// RegisterOrder registers an order listener that retries only on DB lock timeouts.
// Same as RegisterLockTimeoutRetryable. This is a synonym for understanding the
// proposal of RegisterLockTimeoutRetryable.
func (r *ListenerRegistrar) RegisterOrder(l RegistrableListener) {
	if !strings.HasPrefix(l.Name(), "order") {
		panic(fmt.Errorf("the %s should be registered using RegisterRetryable. Please use it instead", l.Name()))
	}
	r.RegisterLockTimeoutRetryable(l)
}

// RegisterLockTimeoutRetryable registers a listener that retries only on DB lock timeouts (SQLSTATE
// 55P03) — e.g. any listener contending with the DLT nonce lock, not just order processes. Its
// concurrency and execution timeout default to the listenerConfig.defaults.lockTimeoutRetryable
// concurrency/executionTimeout values (set once for every such listener across all bounded contexts),
// taking priority over any per-listener or BC config.
func (r *ListenerRegistrar) RegisterLockTimeoutRetryable(l RegistrableListener) {
	var lockRetryDefaults config.ListenerConfigLockTimeoutRetryDefaults
	if config.AppConfig != nil {
		lockRetryDefaults = config.AppConfig.ListenerConfig.Defaults.LockTimeoutRetryable
	}
	r.registry.Register(
		l.EventType(),
		event.NewListenerDefinition(
			l.Name(),
			WrapLockTimeoutRetryableListener(l.AsListener(), r.retryer),
			event.WithConcurrencyLimit(GetListenerConcurrency(l.Name(), r.listenerConfig, lockRetryDefaults.Concurrency)),
			event.WithExecutionTimeout(GetListenerExecutionTimeout(l.Name(), r.listenerConfig, lockRetryDefaults.ExecutionTimeout)),
		),
	)
}
