// Code generated by genqueryname. DO NOT EDIT.

package getfaucetwallet

func (q Query) QueryName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/query/getfaucetwallet.Query"
}

func (q Query) ResponseType() Response { var r Response; return r }
