// Code generated by genrepositories. DO NOT EDIT.

package txqueueslotrepo

import (
	"context"
	"dlt-ingress/src/main/dltingress/internal/domain/txqueueslot"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/db"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/domain/domainerrors"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Creates a new TxQueueSlot into the database.
func (r *Postgres) Create(ctx context.Context, txq *txqueueslot.TxQueueSlot) error {
	rec := FromDomain(*txq)
	if err := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(&rec).Error; err != nil {
		return fmt.Errorf("failed to create TxQueueSlot: %w", err)
	}
	*txq = ToDomain(rec)
	return nil
}

// Save inserts or updates a new TxQueueSlot into the database.
func (r *Postgres) Save(ctx context.Context, txq *txqueueslot.TxQueueSlot) error {
	rec := FromDomain(*txq)
	if err := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(&rec).Error; err != nil {
		return fmt.Errorf("failed to insert TxQueueSlot: %w", err)
	}
	*txq = ToDomain(rec)
	return nil
}

// Delete a TxQueueSlot from the database.
func (r *Postgres) Delete(ctx context.Context, txq *txqueueslot.TxQueueSlot) error {
	rec := FromDomain(*txq)
	if err := r.getDB(ctx).Delete(&rec).Error; err != nil {
		return fmt.Errorf("failed to delete TxQueueSlot: %w", err)
	}
	return nil
}

// FindById returns the TxQueueSlot with the given id.
func (r *Postgres) FindById(ctx context.Context, id uuid.UUID) (*txqueueslot.TxQueueSlot, error) {
	var rec TxQueueSlot
	if err := r.getDB(ctx).First(&rec, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("TxQueueSlot", id)
		}
		return nil, fmt.Errorf("failed to retrieve TxQueueSlot: %w", err)
	}
	txq := ToDomain(rec)
	return &txq, nil
}

// ExistById checks if the TxQueueSlot with the given id exists.
func (r *Postgres) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	var res int
	err := r.getDB(ctx).
		Model(&TxQueueSlot{}).
		Select("1").
		Where("id = ?", id).
		Take(&res).
		Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, nil
		}
		return false, fmt.Errorf("failed to check existence of TxQueueSlot: %w", err)
	}
	return true, nil
}

// FindByIdPreload returns the TxQueueSlot with the given id and all associated entities.
func (r *Postgres) FindByIdPreload(ctx context.Context, id uuid.UUID) (*txqueueslot.TxQueueSlot, error) {
	var rec TxQueueSlot
	if err := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).First(&rec, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("TxQueueSlot", id)
		}
		return nil, fmt.Errorf("failed to retrieve TxQueueSlot: %w", err)
	}
	txq := ToDomain(rec)
	return &txq, nil
}

func recursivePreload(d *gorm.DB, level int) *gorm.DB {
	if level <= 0 {
		return d
	}
	return d.Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, level-1)
	})
}

// FindAll returns all entities TxQueueSlot in the database.
func (r *Postgres) FindAll(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	var recs []TxQueueSlot
	if err := r.getDB(ctx).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch TxQueueSlot entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllWithDeleted returns all entities TxQueueSlot in the database including deleted.
func (r *Postgres) FindAllWithDeleted(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	var recs []TxQueueSlot
	if err := r.getDB(ctx).Unscoped().Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch TxQueueSlot entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllPreload returns all entities TxQueueSlot in the database with all associated entities.
func (r *Postgres) FindAllPreload(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	var recs []TxQueueSlot
	if err := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch TxQueueSlot entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllPaginated returns all entities TxQueueSlot in the database, paginated.
func (r *Postgres) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]txqueueslot.TxQueueSlot, error) {
	var recs []TxQueueSlot
	if err := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch TxQueueSlot entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllPaginatedPreload returns all entities TxQueueSlot in the database with all associated entities, paginated.
func (r *Postgres) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]txqueueslot.TxQueueSlot, error) {
	var recs []TxQueueSlot
	if err := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch TxQueueSlot entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// CountAll returns the number of entities TxQueueSlot in the database.
func (r *Postgres) CountAll(ctx context.Context) (int, error) {
	var count int64
	if err := r.getDB(ctx).Model(&TxQueueSlot{}).Count(&count).Error; err != nil {
		return 0, fmt.Errorf("failed to count TxQueueSlot entities: %w", err)
	}
	return int(count), nil
}

func (r *Postgres) getDB(ctx context.Context) *gorm.DB {
	val := r.tm.TransactionValue(ctx)
	if val == nil {
		return r.db
	}

	wrapper, ok := val.(db.GormTransaction)
	if !ok {
		return r.db
	}

	wrapperTx := wrapper.Tx
	txDb, errTx := wrapperTx.DB()
	repoDb, errDb := r.db.DB()

	if errTx == nil && errDb == nil && txDb == repoDb {
		return wrapperTx
	}

	return r.db
}

var _ txqueueslot.Repository = (*Postgres)(nil)
