// Code generated by gencommandname. DO NOT EDIT.

package updatefaucetwallet

func (c *Command) CommandName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/command/updatefaucetwallet.Command"
}
