package test

import (
	"context"
	"dlt-ingress/src/main/config"
	"log/slog"
	"math/rand"
	//"dlt-ingress/src/test/entitymgmt/domain/account"
	//testactorfactory "dlt-ingress/src/test/entitymgmt/domain/entity"
	//testactoraccountfactory "dlt-ingress/src/test/entitymgmt/domain/entityaccount"
	//testuserfactory "dlt-ingress/src/test/entitymgmt/domain/user"
	blockchainmocks "dlt-ingress/src/test/blockchain/port/repository"
	testcomplianceeligibilityexternallistfactory "dlt-ingress/src/test/compliance/domain/complianceeligibility/externallist"
	testcomplianceeligibilityexternallistaccountfactory "dlt-ingress/src/test/compliance/domain/complianceeligibility/externallistaccount"
	compliancemocks "dlt-ingress/src/test/compliance/port/repository"
	blockchainmock "dlt-ingress/src/test/core/blockchain"
	mocks "dlt-ingress/src/test/core/port/repository"
	testallocationfactory "dlt-ingress/src/test/primarymarket/domain/allocation"
	testinstrumenthubfactory "dlt-ingress/src/test/primarymarket/domain/instrument"
	testofferingfactory "dlt-ingress/src/test/primarymarket/domain/offering"
	testprimarymarketfactory "dlt-ingress/src/test/primarymarket/domain/primarymarket"
	testcancelsubscriptionfactory "dlt-ingress/src/test/primarymarket/domain/process/cancelsubscription"
	testsubscriptionfactory "dlt-ingress/src/test/primarymarket/domain/subscription"
	primarymarketmocks "dlt-ingress/src/test/primarymarket/port/repository"
	testholdfactory "dlt-ingress/src/test/registry/domain/hold"
	testhistoricalpositionrecordfactory "dlt-ingress/src/test/registry/domain/ownership/historicalpositionrecord"
	testpositionfactory "dlt-ingress/src/test/registry/domain/position"
	testburnProcessFactory "dlt-ingress/src/test/registry/domain/process/burn"
	testtransferProcessFactory "dlt-ingress/src/test/registry/domain/process/transfer"
	testtransactionfactory "dlt-ingress/src/test/registry/domain/transaction"
	registrymocks "dlt-ingress/src/test/registry/port/repository"
	testinstructionfactory "dlt-ingress/src/test/settlement/domain/instruction"
	testcancellationinstructionfactory "dlt-ingress/src/test/settlement/domain/instruction/cancellation"
	testsettlementinstructionfactory "dlt-ingress/src/test/settlement/domain/instruction/settlement"
	servicemocksettlementinstruction "dlt-ingress/src/test/settlement/domain/instruction/settlement/servicemock"
	testcreatesettlementinstructionprocessfactory "dlt-ingress/src/test/settlement/domain/process/createsettlementinstruction"
	testcreatesettlementtransactionprocessfactory "dlt-ingress/src/test/settlement/domain/process/createsettlementtransaction"
	testexecutesettlementprocessfactory "dlt-ingress/src/test/settlement/domain/process/executesettlement"
	testexecuteinstructioncancellationfactory "dlt-ingress/src/test/settlement/domain/process/instructioncancellation"
	testexecuteinstructionexpirationfactory "dlt-ingress/src/test/settlement/domain/process/instructionexpiration"
	testsettlementfactory "dlt-ingress/src/test/settlement/domain/settlement"
	testsettlementexecutionfactory "dlt-ingress/src/test/settlement/domain/settlementexecution"
	testsettlementhubfactory "dlt-ingress/src/test/settlement/domain/settlementhub"
	testsettlementhubassetfactory "dlt-ingress/src/test/settlement/domain/settlementhub/settlementhubasset"
	testsettlementoptionfactory "dlt-ingress/src/test/settlement/domain/settlementoption"
	testsettlementprimarymarketfactory "dlt-ingress/src/test/settlement/domain/settlementprimarymarket"
	testsettlementtransactionfactory "dlt-ingress/src/test/settlement/domain/transaction/settlement"
	settlementmocks "dlt-ingress/src/test/settlement/port/repository"
	testsharedassetfactory "dlt-ingress/src/test/shared/domain/asset"
	testsharedassetclassfactory "dlt-ingress/src/test/shared/domain/assetclass"
	testsharedassetcomplianceeligibilityexternallistfactory "dlt-ingress/src/test/shared/domain/assetcomplianceeligibilityexternallist"
	testsharedcalendarfactory "dlt-ingress/src/test/shared/domain/calendar"
	testsharedcapabilityfactory "dlt-ingress/src/test/shared/domain/capability"
	testsharedcomplianceeligibilityaccountfactory "dlt-ingress/src/test/shared/domain/complianceeligibilityaccount"
	testsharedcomplianceeligibilityexternallistfactory "dlt-ingress/src/test/shared/domain/complianceeligibilityexternallist"
	testsharedcomplianceeligibilityexternallistaccountfactory "dlt-ingress/src/test/shared/domain/complianceeligibilityexternallistaccount"
	testsharedapprovalfactory "dlt-ingress/src/test/shared/domain/process/approval"
	sharedmocks "dlt-ingress/src/test/shared/port/repository"

	"os"
	"testing"

	commandcrossbusmock "dlt-ingress/src/test/core/command"

	"github.com/ethereum/go-ethereum/common"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/event"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/logger"
	commandbusmock "gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/test/core/command"
	testbus "gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/test/core/event"
	coremocks "gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/test/core/port/repository"
	querybusmock "gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/test/core/query"

	_ "github.com/lib/pq"
	"github.com/stretchr/testify/mock"
)

// var MockAssetRepo *issuancemocks.AssetRepositoryMock
// var MockHoldingsAssetRepo *issuancemocks.HoldingsAssetRepositoryMock
// var MockDocumentRepo *issuancemocks.DocumentRepositoryMock
// var MockBasicBondRepo *issuancemocks.BasicBondRepositoryMock
// var MockTokenizedCreditRepo *issuancemocks.TokenizedCreditRepositoryMock
// var MockTokenizedCreditCollateralRepo *issuancemocks.TokenizedCreditCollateralRepositoryMock
// var MockTokenizedCreditLoanDeedRepo *issuancemocks.TokenizedCreditLoanDeedRepositoryMock
// var MockTokenizedCreditLoanRiskRepo *issuancemocks.TokenizedCreditLoanRiskRepositoryMock
// var MockTokenizedCreditPerformanceStatusRepo *issuancemocks.TokenizedCreditPerformanceStatusRepositoryMock
// var MockAssetPartyRepo *issuancemocks.AssetPartyRepositoryMock
// var MockCouponDefinitionRepo *issuancemocks.CouponDefinitionRepositoryMock
// var MockLoansPortfolioRepo *issuancemocks.LoansPortfolioRepositoryMock
// var MockCreateAssetProcessRepo *issuancemocks.CreateAssetProcessRepositoryMock
// var MockManageAssetRolesProcessRepo *issuancemocks.ManageAssetRolesProcessRepositoryMock
// var MockUploadDocumentProcessRepo *issuancemocks.UploadDocumentProcessRepositoryMock
// var MockDeleteDocumentProcessRepo *issuancemocks.DeleteDocumentProcessRepositoryMock
// var MockAddHoldingsAssetProcessRepo *issuancemocks.AddHoldingsAssetProcessRepositoryMock
// var MockAddComplianceEligibilityAccountProcessRepo *issuancemocks.AddComplianceEligibilityAccountProcessRepositoryMock
// var MockAddComplianceEligibilityExternalListProcessRepo *issuancemocks.AddComplianceEligibilityExternalListProcessRepositoryMock
// var MockRemoveComplianceEligibilityExternalListProcessRepo *issuancemocks.RemoveComplianceEligibilityExternalListProcessRepositoryMock
// var MockComplianceEligibilityAccountRepo *issuancemocks.ComplianceEligibilityAccountRepositoryMock
// var MockPauseAssetProcessRepo *issuancemocks.PauseAssetProcessRepositoryMock
// var MockUnpauseAssetProcessRepo *issuancemocks.UnpauseAssetProcessRepositoryMock
// var MockRemoveHoldingsAssetProcessRepo *issuancemocks.RemoveHoldingsAssetProcessRepositoryMock
// var MockRemoveComplianceEligibilityAccountProcessRepo *issuancemocks.RemoveComplianceEligibilityAccountProcessRepositoryMock
var MockMintProcessRepo *registrymocks.MintProcessRepositoryMock
var MockBurnProcessRepo *registrymocks.BurnProcessRepositoryMock
var MockTransferProcessRepo *registrymocks.TransferProcessRepositoryMock
var MockWithdrawProcessRepo *registrymocks.WithdrawProcessRepositoryMock
var MockPositionRepo *registrymocks.PositionRepositoryMock
var MockHoldRepo *registrymocks.HoldRepositoryMock
var MockResolutionHistoryRepo *registrymocks.ResolutionHistoryRepositoryMock

// var MockAssetDltRoleRepo *issuancemocks.AssetDltRoleRepositoryMock
// var MockAssetRoleAssociationRepo *issuancemocks.AssetRoleAssociationRepositoryMock
var MockDltRoleRepo *mocks.DltRoleRepositoryMock

/*
var MockCouponLifecycleEventRepo *assetlifecyclemocks.CouponLifecycleEventRepositoryMock
var MockAmortizationLifecycleEventRepo *assetlifecyclemocks.AmortizationLifecycleEventRepositoryMock
var MockCreateLifecycleEventProcessRepo *assetlifecyclemocks.CreateLifecycleEventProcessRepositoryMock
var MockPaymentLifecycleEventProcessRepo *assetlifecyclemocks.PaymentLifecycleEventProcessRepositoryMock
var MockPaymentGroupLifecycleEventProcessRepo *assetlifecyclemocks.PaymentGroupLifecycleEventProcessRepositoryMock
var MockPaymentLifecycleEventRepo *assetlifecyclemocks.PaymentLifecycleEventRepositoryMock
var MockLifecycleEventRepo *assetlifecyclemocks.LifecycleEventRepositoryMock
var MockPositionsRecordLifecycleEventRepo *assetlifecyclemocks.PositionsRecordLifecycleEventRepositoryMock
var MockUploadLifecycleDocumentProcessRepo *assetlifecyclemocks.UploadDocumentProcessRepositoryMock
var MockDeleteLifecycleDocumentProcessRepo *assetlifecyclemocks.DeleteDocumentProcessRepositoryMock
var MockLifecycleEventDocumentRepo *assetlifecyclemocks.DocumentRepositoryMock
var MockCreatePositionsRecordLifecycleEventProcessRepo *assetlifecyclemocks.CreatePositionsRecordLifecycleEventProcessRepositoryMock
var MockPositionPositionsRecordRepo *assetlifecyclemocks.PositionPositionsRecordLifecycleEventRepositoryMock
var MockAddHoldingsAssetLifecycleEventProcessRepo *assetlifecyclemocks.AddHoldingsAssetLifecycleEventProcessRepositoryMock
var MockCreateRepaymentLifecycleEventProcessRepo *assetlifecyclemocks.CreateRepaymentLifecycleEventProcessRepositoryMock
var MockHoldingsAssetLifecycleEventRepo *assetlifecyclemocks.HoldingsAssetLifecycleEventRepositoryMock
var MockHoldingsAssetPaymentLifecycleEventRepo *assetlifecyclemocks.HoldingsAssetPaymentLifecycleEventRepositoryMock
var MockCancelLifecycleEventProcessRepo *assetlifecyclemocks.CancelLifecycleEventProcessRepositoryMock
*/
var MockEventFilterRepo *blockchainmocks.EventFilterRepositoryMock
var MockTransactionFilterRepo *blockchainmocks.TransactionFilterRepositoryMock
var MockLatestBlockRepo *blockchainmocks.LatestBlockRepositoryMock

var MockTransactionRepo *registrymocks.TransactionRepositoryMock

// var MockIssuanceProcessRepo *issuancemocks.BaseProcessRepositoryMock
var MockBaseProcessRepo *coremocks.BaseProcessRepositoryMock
var MockQueryBus *querybusmock.QueryBusMock
var MockEventBus *testbus.EventBusMock
var MockCommandBus *commandbusmock.CommandBusMock
var MockCrossCommandBus *commandcrossbusmock.CrossBusMock
var MockBlockchainClientService *blockchainmock.ServiceMock
var MockRegistryProcessRepo *registrymocks.BaseProcessRepositoryMock
var MockCreatePrimaryMarketProcessRepo *primarymarketmocks.CreatePrimaryMarketProcessRepositoryMock
var MockRegisterSettlementOptionProcessRepo *settlementmocks.RegisterSettlementOptionProcessRepositoryMock
var MockPrimaryMarketRepo *primarymarketmocks.PrimaryMarketRepositoryMock
var MockListInstrumentProcessRepo *primarymarketmocks.ListInstrumentProcessRepositoryMock
var MockInstrumentRepo *primarymarketmocks.InstrumentRepositoryMock
var MockCreateSettlementHubProcessRepo *settlementmocks.CreateSettlementHubProcessRepositoryMock
var MockSettlementHubRepo *settlementmocks.SettlementHubRepositoryMock
var MockSettlementOptionRepo *settlementmocks.SettlementOptionRepositoryMock
var MockCreateOfferingProcessRepo *primarymarketmocks.CreateOfferingProcessRepositoryMock
var MockOfferingRepo *primarymarketmocks.OfferingRepositoryMock
var MockCloseOfferingProcessRepo *primarymarketmocks.CloseOfferingProcessRepositoryMock
var MockAddSubscriptionProcessRepo *primarymarketmocks.AddSubscriptionProcessRepositoryMock
var MockSubscriptionRepo *primarymarketmocks.SubscriptionRepositoryMock
var MockSettlementPrimaryMarketRepo *settlementmocks.SettlementPrimaryMarketRepositoryMock
var MockRegisterPrimaryMarketProcessRepo *settlementmocks.RegisterPrimaryMarketProcessRepositoryMock
var MockPauseSettlementHubProcessRepo *settlementmocks.PauseSettlementHubProcessRepositoryMock
var MockResumeSettlementHubProcessRepo *settlementmocks.ResumeSettlementHubProcessRepositoryMock
var MockPausePrimaryMarketProcessRepo *primarymarketmocks.PausePrimaryMarketProcessRepositoryMock
var MockResumePrimaryMarketProcessRepo *primarymarketmocks.ResumePrimaryMarketProcessRepositoryMock
var MockAllocationProcessRepo *primarymarketmocks.AllocationProcessRepositoryMock
var MockAllocationRepo *primarymarketmocks.AllocationRepositoryMock
var MockSettleAllocationProcessRepo *primarymarketmocks.SettleAllocationProcessRepositoryMock
var MockSettlementRepo *settlementmocks.SettlementRepositoryMock
var MockCancelAllocationProcessRepo *primarymarketmocks.CancelAllocationProcessRepositoryMock

// var MockInterestPaymentLifecycleEventRepo *assetlifecyclemocks.InterestPaymentLifecycleEventRepositoryMock
// var MockRedemptionPaymentLifecycleEventRepo *assetlifecyclemocks.RedemptionPaymentLifecycleEventRepositoryMock
var MockHistoricalPositionRecordRepo *registrymocks.HistoricalPositionRecordRepositoryMock
var MockAssignAssetToSettlementHubProcessRepo *settlementmocks.AssignAssetToSettlementHubProcessRepositoryMock
var MockSettlementHubAssetRepo *settlementmocks.SettlementHubAssetRepositoryMock
var MockCreateSettlementInstructionProcessRepo *settlementmocks.CreateSettlementInstructionProcessRepositoryMock
var MockCreateSettlementTransactionProcessRepo *settlementmocks.CreateSettlementTransactionProcessRepositoryMock
var MockExecuteInstructionExpirationProcessRepo *settlementmocks.ExecuteInstructionExpirationProcessRepositoryMock
var MockExecuteInstructionCancellationProcessRepo *settlementmocks.ExecuteInstructionCancellationProcessRepositoryMock
var MockCancelSubscriptionProcessRepo *primarymarketmocks.CancelSubscriptionProcessRepositoryMock
var MockCreateCancellationInstructionProcessRepo *settlementmocks.CreateCancellationInstructionProcessRepositoryMock
var MockSettlementInstructionRepo *settlementmocks.SettlementInstructionRepositoryMock
var MockMetadataInstructionRepo *settlementmocks.MetadataInstructionRepositoryMock
var MockSettlementInstructionExists *servicemocksettlementinstruction.ExistsMock
var MockSettlementTransactionRepo *settlementmocks.SettlementTransactionRepositoryMock
var MockInstructionRepo *settlementmocks.InstructionRepositoryMock
var MockApprovalProcess *sharedmocks.ApprovalProcessRepositoryMock
var MockMatchingProcessRepo *settlementmocks.MatchingProcessRepositoryMock
var MockAddComplianceEligibilityExternalListAccountProcessRepo *compliancemocks.AddComplianceEligibilityExternalListAccountProcessRepositoryMock
var MockComplianceEligibilityExternalListAccountRepo *compliancemocks.ComplianceEligibilityExternalListAccountRepositoryMock
var MockComplianceEligibilityExternalListRepo *compliancemocks.ComplianceEligibilityExternalListRepositoryMock
var MockRemoveComplianceEligibilityExternalListAccountProcessRepo *compliancemocks.RemoveComplianceEligibilityExternalListAccountProcessRepositoryMock
var MockExecuteSettlementProcessRepo *settlementmocks.ExecuteSettlementProcessRepositoryMock
var MockSettlementExecutionRepo *settlementmocks.SettlementExecutionRepositoryMock
var MockCreateComplianceEligibilityExternalListProcessRepo *compliancemocks.CreateComplianceEligibilityExternalListProcessRepositoryMock
var MockCreateHoldProcessRepo *registrymocks.CreateHoldProcessRepositoryMock
var MockCancellationInstructionRepo *settlementmocks.CancellationInstructionRepositoryMock
var MockExecuteHoldProcessRepo *registrymocks.ExecuteHoldProcessRepositoryMock

// var MockAssetComplianceEligibilityExternalListRepo *issuancemocks.AssetComplianceEligibilityExternalListRepositoryMock
var MockSharedAssetComplianceEligibilityExternalListRepo *sharedmocks.AssetComplianceEligibilityExternalListRepositoryMock
var MockReclaimHoldProcessRepo *registrymocks.ReclaimHoldProcessRepositoryMock
var MockReleaseHoldProcessRepo *registrymocks.ReleaseHoldProcessRepositoryMock

var MockSharedComplianceEligibilityAccountRepo *sharedmocks.ComplianceEligibilityAccountRepositoryMock
var MockSharedComplianceEligibilityExternalListRepo *sharedmocks.ComplianceEligibilityExternalListRepositoryMock
var MockSharedComplianceEligibilityExternalListAccountRepo *sharedmocks.ComplianceEligibilityExternalListAccountRepositoryMock
var MockSharedAssetRepo *sharedmocks.AssetRepositoryMock
var MockSharedAssetClassRepo *sharedmocks.AssetClassRepositoryMock
var MockSharedCapabilityRepo *sharedmocks.CapabilityRepositoryMock

//var MockCountryCheck *servicemockissuance.CheckCountryCodeServiceMock

// var EntityFactory *testactorfactory.EntityTestFactory
// var AccountFactory *account.AccountTestFactory
// var EntityAccountFactory *testactoraccountfactory.EntityAccountTestFactory
// var UserFactory *testuserfactory.UserTestFactory
// var AssetFactory *testassetfactory.AssetTestFactory
// var AssetDltRoleFactory *testassetdltrolefactory.AssetDltRoleTestFactory
// var AssetRoleAssociationFactory *testassetroleassociationfactory.AssetRoleAssociationTestFactory
// var DocumentFactory *testdocumentfactory.DocumentTestFactory

// var AssetLifecycleDocumentFactory *testassetlifecycledocumentfactory.DocumentTestFactory
// var BasicBondFactory *testbasicbondfactory.BasicBondTestFactory
// var TokenizedCreditFactory *testtokenizedcreditfactory.TokenizedCreditTestFactory
// var CouponDefinitionFactory *testcoupondefinitionfactory.CouponDefinitionTestFactory
// var LoansPortfolioFactory *testloansportfoliofactory.LoansPortfolioTestFactory
// var CreateAssetProcessFactory *testcreateassetprocessfactory.CreateAssetProcessTestFactory
var PositionFactory *testpositionfactory.PositionTestFactory
var TransactionFactory *testtransactionfactory.TransactionTestFactory
var BurnProcessFactory *testburnProcessFactory.BurnProcessTestFactory
var TransferProcessFactory *testtransferProcessFactory.TransferProcessTestFactory
var SettlementHubFactory *testsettlementhubfactory.SettlementHubTestFactory
var SettlementHubAssetFactory *testsettlementhubassetfactory.SettlementHubAssetTestFactory
var CancellationInstructionFactory *testcancellationinstructionfactory.CancellationInstructionTestFactory
var SettlementPrimaryMarketFactory *testsettlementprimarymarketfactory.SettlementPrimaryMarketTestFactory
var SettlementInstructionFactory *testsettlementinstructionfactory.SettlementInstructionTestFactory
var SettlementTransactionFactory *testsettlementtransactionfactory.SettlementTransactionTestFactory
var InstrumentFactory *testinstrumenthubfactory.InstrumentTestFactory
var PrimaryMarketFactory *testprimarymarketfactory.PrimaryMarketTestFactory
var SettlementOptionFactory *testsettlementoptionfactory.SettlementOptionTestFactory
var CreateSettlementInstructionProcessFactory *testcreatesettlementinstructionprocessfactory.CreateSettlementInstructionProcessTestFactory
var CreateSettlementTransactionProcessFactory *testcreatesettlementtransactionprocessfactory.CreateSettlementTransactionProcessTestFactory
var ExecuteInstructionExpirationProcessFactory *testexecuteinstructionexpirationfactory.ExecuteInstructionExpirationProcessTestFactory
var ExecuteInstructionCancellationProcessFactory *testexecuteinstructioncancellationfactory.ExecuteInstructionCancellationProcessTestFactory
var CancelSubscriptionProcessFactory *testcancelsubscriptionfactory.CancelSubscriptionProcessTestFactory
var ExecuteSettlementProcessFactory *testexecutesettlementprocessfactory.ExecuteSettlementProcessTestFactory
var SettlementExecutionFactory *testsettlementexecutionfactory.SettlementExecutionTestFactory
var OfferingFactory *testofferingfactory.OfferingTestFactory
var SubscriptionFactory *testsubscriptionfactory.SubscriptionTestFactory
var SettlementFactory *testsettlementfactory.SettlementTestFactory
var AllocationFactory *testallocationfactory.AllocationTestFactory

/*
var LifecycleEventFactory *lifecycleevent.LifecycleEventFactory
var AmortizationLifecycleEventFactory *amortizationlifecycleevent.AmortizationLifecycleEventFactory
var CouponLifecycleEventFactory *couponlifecycleevent.CouponLifecycleEventFactory
var InterestPaymentLifecycleEventFactory *interestpaymentlifecycleevent.InterestPaymentLifecycleEventFactory
var RedemptionPaymentLifecycleEventFactory *redemptionpaymentlifecycleevent.RedemptionPaymentLifecycleEventFactory
var PositionPositionsRecordFactory *positionpositionsrecord.PositionTestFactory
var PositionsRecordFactory *positionsrecordlifecycleevent.PositionsRecordTestFactory
var PaymentLifecycleEventFactory *paymentlifecycleevent.PaymentTestFactory
*/
// var HoldingsAssetFactory *testholdingsassetfactory.HoldingsAssetTestFactory
var HistoricalPositionRecordFactory *testhistoricalpositionrecordfactory.HistoricalPositionRecordTestFactory
var InstructionFactory *testinstructionfactory.InstructionTestFactory
var ApprovalFactory *testsharedapprovalfactory.ApprovalProcessTestFactory

// var ComplianceEligibilityAccountFactory *testcomplianceeligibilityaccountprocessfactory.ComplianceEligibilityAccountTestFactory
var ComplianceEligibilityExternalListFactory *testcomplianceeligibilityexternallistfactory.ComplianceEligibilityExternalListTestFactory
var ComplianceEligibilityExternalListAccountFactory *testcomplianceeligibilityexternallistaccountfactory.ComplianceEligibilityExternalListAccountTestFactory

// var AssetComplianceEligibilityExternalListFactory *testassetcomplianceeligibilityexternallistfactory.ComplianceEligibilityExternalListTestFactory
var HoldFactory *testholdfactory.HoldTestFactory

var SharedAssetComplianceEligibilityExternalListRepo *sharedmocks.AssetComplianceEligibilityExternalListRepositoryMock
var SharedComplianceEligibilityAccountFactory *testsharedcomplianceeligibilityaccountfactory.ComplianceEligibilityAccountTestFactory
var SharedComplianceEligibilityExternalListFactory *testsharedcomplianceeligibilityexternallistfactory.ComplianceEligibilityExternalListTestFactory
var SharedComplianceEligibilityExternalListAccountFactory *testsharedcomplianceeligibilityexternallistaccountfactory.ComplianceEligibilityExternalListAccountTestFactory
var SharedAssetComplianceEligibilityExternalListFactory *testsharedassetcomplianceeligibilityexternallistfactory.ComplianceEligibilityExternalListTestFactory
var SharedAssetFactory *testsharedassetfactory.AssetTestFactory
var SharedAssetClassFactory *testsharedassetclassfactory.AssetClassTestFactory
var SharedCalendarFactory *testsharedcalendarfactory.CalendarTestFactory
var SharedCapabilityFactory *testsharedcapabilityfactory.CapabilityTestFactory

const EXAMPLE_PRIVATE_KEY = "82b9bbfaa384d32a4cfa4a56664c667299228bd74b9332f5e2c8ee372e6246ce"

var EXAMPLE_CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000"
var EVM_ZERO_ADDRESS = "0x0"
var RANDOM_ADDRESS = "0x123456789"

var DefaultPaginationParams = pagination.PaginationParams{
	PageSize: 10,
	Offset:   0,
	SortBy:   "created_at",
	SortDir:  "DESC",
}

func RandomAddress() string {
	b := make([]byte, 20)
	rand.Read(b)
	return common.BytesToAddress(b).Hex()
}

func TestSetup() {
	os.Setenv("API_ENVIRONMENT", "test")
	os.Setenv("ASSETO_RETRYABLE_MAX_ATTEMPTS", "1")
	CleanUpMocks()
	os.Unsetenv("API_ENVIRONMENT")

	logger.SetDefaultLogger(logger.NewSlogLogger(slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))))
	if err := config.LoadConfig(context.Background()); err != nil {
		logger.Error("failed to load configuration", "error", err)
		os.Exit(1)
	}
}

func CleanUpMocks() {
	//MockEntityRepo = new(entitymocks.EntityRepositoryMock)
	//MockAccountRepo = new(mock3.AccountRepositoryMock)
	//MockUserRepo = new(mock2.UserRepositoryMock)
	// MockAssetRepo = new(issuancemocks.AssetRepositoryMock)
	// MockHoldingsAssetRepo = new(issuancemocks.HoldingsAssetRepositoryMock)
	// MockDocumentRepo = new(issuancemocks.DocumentRepositoryMock)
	// MockBasicBondRepo = new(issuancemocks.BasicBondRepositoryMock)
	// MockTokenizedCreditRepo = new(issuancemocks.TokenizedCreditRepositoryMock)
	// MockTokenizedCreditCollateralRepo = new(issuancemocks.TokenizedCreditCollateralRepositoryMock)
	// MockTokenizedCreditLoanRiskRepo = new(issuancemocks.TokenizedCreditLoanRiskRepositoryMock)
	// MockTokenizedCreditLoanDeedRepo = new(issuancemocks.TokenizedCreditLoanDeedRepositoryMock)
	// MockTokenizedCreditPerformanceStatusRepo = new(issuancemocks.TokenizedCreditPerformanceStatusRepositoryMock)
	// MockAssetPartyRepo = new(issuancemocks.AssetPartyRepositoryMock)
	// MockCouponDefinitionRepo = new(issuancemocks.CouponDefinitionRepositoryMock)
	// MockLoansPortfolioRepo = new(issuancemocks.LoansPortfolioRepositoryMock)
	// MockCreateAssetProcessRepo = new(issuancemocks.CreateAssetProcessRepositoryMock)
	// MockUploadDocumentProcessRepo = new(issuancemocks.UploadDocumentProcessRepositoryMock)
	// MockDeleteDocumentProcessRepo = new(issuancemocks.DeleteDocumentProcessRepositoryMock)
	// MockAddHoldingsAssetProcessRepo = new(issuancemocks.AddHoldingsAssetProcessRepositoryMock)
	// MockAddComplianceEligibilityAccountProcessRepo = new(issuancemocks.AddComplianceEligibilityAccountProcessRepositoryMock)
	// MockAddComplianceEligibilityExternalListProcessRepo = new(issuancemocks.AddComplianceEligibilityExternalListProcessRepositoryMock)
	// MockRemoveComplianceEligibilityExternalListProcessRepo = new(issuancemocks.RemoveComplianceEligibilityExternalListProcessRepositoryMock)
	// MockComplianceEligibilityAccountRepo = new(issuancemocks.ComplianceEligibilityAccountRepositoryMock)
	// MockPauseAssetProcessRepo = new(issuancemocks.PauseAssetProcessRepositoryMock)
	// MockUnpauseAssetProcessRepo = new(issuancemocks.UnpauseAssetProcessRepositoryMock)
	// MockRemoveHoldingsAssetProcessRepo = new(issuancemocks.RemoveHoldingsAssetProcessRepositoryMock)
	// MockRemoveComplianceEligibilityAccountProcessRepo = new(issuancemocks.RemoveComplianceEligibilityAccountProcessRepositoryMock)
	/*
		MockLifecycleEventRepo = new(assetlifecyclemocks.LifecycleEventRepositoryMock)
		MockPaymentLifecycleEventProcessRepo = new(assetlifecyclemocks.PaymentLifecycleEventProcessRepositoryMock)
		MockPaymentGroupLifecycleEventProcessRepo = new(assetlifecyclemocks.PaymentGroupLifecycleEventProcessRepositoryMock)
		MockPaymentLifecycleEventRepo = new(assetlifecyclemocks.PaymentLifecycleEventRepositoryMock)
		MockLifecycleEventDocumentRepo = new(assetlifecyclemocks.DocumentRepositoryMock)
		MockCouponLifecycleEventRepo = new(assetlifecyclemocks.CouponLifecycleEventRepositoryMock)
		MockPositionsRecordLifecycleEventRepo = new(assetlifecyclemocks.PositionsRecordLifecycleEventRepositoryMock)
		MockUploadLifecycleDocumentProcessRepo = new(assetlifecyclemocks.UploadDocumentProcessRepositoryMock)
		MockDeleteLifecycleDocumentProcessRepo = new(assetlifecyclemocks.DeleteDocumentProcessRepositoryMock)
		MockCreatePositionsRecordLifecycleEventProcessRepo = new(assetlifecyclemocks.CreatePositionsRecordLifecycleEventProcessRepositoryMock)
		MockAmortizationLifecycleEventRepo = new(assetlifecyclemocks.AmortizationLifecycleEventRepositoryMock)
		MockCreateLifecycleEventProcessRepo = new(assetlifecyclemocks.CreateLifecycleEventProcessRepositoryMock)
		MockPositionPositionsRecordRepo = new(assetlifecyclemocks.PositionPositionsRecordLifecycleEventRepositoryMock)
		MockAddHoldingsAssetLifecycleEventProcessRepo = new(assetlifecyclemocks.AddHoldingsAssetLifecycleEventProcessRepositoryMock)
		MockCreateRepaymentLifecycleEventProcessRepo = new(assetlifecyclemocks.CreateRepaymentLifecycleEventProcessRepositoryMock)
		MockHoldingsAssetLifecycleEventRepo = new(assetlifecyclemocks.HoldingsAssetLifecycleEventRepositoryMock)
		MockHoldingsAssetPaymentLifecycleEventRepo = new(assetlifecyclemocks.HoldingsAssetPaymentLifecycleEventRepositoryMock)
		MockInterestPaymentLifecycleEventRepo = new(assetlifecyclemocks.InterestPaymentLifecycleEventRepositoryMock)
		MockRedemptionPaymentLifecycleEventRepo = new(assetlifecyclemocks.RedemptionPaymentLifecycleEventRepositoryMock)
		MockCancelLifecycleEventProcessRepo = new(assetlifecyclemocks.CancelLifecycleEventProcessRepositoryMock)
	*/
	// MockIssuanceProcessRepo = new(issuancemocks.BaseProcessRepositoryMock)
	MockMintProcessRepo = new(registrymocks.MintProcessRepositoryMock)
	MockBurnProcessRepo = new(registrymocks.BurnProcessRepositoryMock)
	MockTransferProcessRepo = new(registrymocks.TransferProcessRepositoryMock)
	MockWithdrawProcessRepo = new(registrymocks.WithdrawProcessRepositoryMock)
	MockPositionRepo = new(registrymocks.PositionRepositoryMock)
	MockHoldRepo = new(registrymocks.HoldRepositoryMock)
	MockResolutionHistoryRepo = new(registrymocks.ResolutionHistoryRepositoryMock)
	MockTransactionRepo = new(registrymocks.TransactionRepositoryMock)
	// MockAssetDltRoleRepo = new(issuancemocks.AssetDltRoleRepositoryMock)
	// MockAssetRoleAssociationRepo = new(issuancemocks.AssetRoleAssociationRepositoryMock)
	MockDltRoleRepo = new(mocks.DltRoleRepositoryMock)

	MockEventFilterRepo = new(blockchainmocks.EventFilterRepositoryMock)
	MockTransactionFilterRepo = new(blockchainmocks.TransactionFilterRepositoryMock)
	MockLatestBlockRepo = new(blockchainmocks.LatestBlockRepositoryMock)
	MockCancellationInstructionRepo = new(settlementmocks.CancellationInstructionRepositoryMock)

	MockRegistryProcessRepo = new(registrymocks.BaseProcessRepositoryMock)
	// MockManageAssetRolesProcessRepo = new(issuancemocks.ManageAssetRolesProcessRepositoryMock)
	//MockCountryCheck = new(servicemockissuance.CheckCountryCodeServiceMock)
	MockBaseProcessRepo = new(coremocks.BaseProcessRepositoryMock)
	MockQueryBus = new(querybusmock.QueryBusMock)
	MockEventBus = new(testbus.EventBusMock)
	MockCommandBus = new(commandbusmock.CommandBusMock)
	MockCrossCommandBus = new(commandcrossbusmock.CrossBusMock)
	MockBlockchainClientService = new(blockchainmock.ServiceMock)
	MockCreatePrimaryMarketProcessRepo = new(primarymarketmocks.CreatePrimaryMarketProcessRepositoryMock)
	MockRegisterSettlementOptionProcessRepo = new(settlementmocks.RegisterSettlementOptionProcessRepositoryMock)
	MockPrimaryMarketRepo = new(primarymarketmocks.PrimaryMarketRepositoryMock)
	MockListInstrumentProcessRepo = new(primarymarketmocks.ListInstrumentProcessRepositoryMock)
	MockInstrumentRepo = new(primarymarketmocks.InstrumentRepositoryMock)
	MockSettlementOptionRepo = new(settlementmocks.SettlementOptionRepositoryMock)
	MockCreateOfferingProcessRepo = new(primarymarketmocks.CreateOfferingProcessRepositoryMock)
	MockCreateSettlementHubProcessRepo = new(settlementmocks.CreateSettlementHubProcessRepositoryMock)
	MockSettlementHubRepo = new(settlementmocks.SettlementHubRepositoryMock)
	MockCreateOfferingProcessRepo = new(primarymarketmocks.CreateOfferingProcessRepositoryMock)
	MockOfferingRepo = new(primarymarketmocks.OfferingRepositoryMock)
	MockCloseOfferingProcessRepo = new(primarymarketmocks.CloseOfferingProcessRepositoryMock)
	MockAddSubscriptionProcessRepo = new(primarymarketmocks.AddSubscriptionProcessRepositoryMock)
	MockSubscriptionRepo = new(primarymarketmocks.SubscriptionRepositoryMock)
	MockSettlementPrimaryMarketRepo = new(settlementmocks.SettlementPrimaryMarketRepositoryMock)
	MockRegisterPrimaryMarketProcessRepo = new(settlementmocks.RegisterPrimaryMarketProcessRepositoryMock)
	MockPauseSettlementHubProcessRepo = new(settlementmocks.PauseSettlementHubProcessRepositoryMock)
	MockResumeSettlementHubProcessRepo = new(settlementmocks.ResumeSettlementHubProcessRepositoryMock)
	MockPausePrimaryMarketProcessRepo = new(primarymarketmocks.PausePrimaryMarketProcessRepositoryMock)
	MockResumePrimaryMarketProcessRepo = new(primarymarketmocks.ResumePrimaryMarketProcessRepositoryMock)
	MockSettlementHubAssetRepo = new(settlementmocks.SettlementHubAssetRepositoryMock)
	MockAllocationProcessRepo = new(primarymarketmocks.AllocationProcessRepositoryMock)
	MockAllocationRepo = new(primarymarketmocks.AllocationRepositoryMock)
	MockSettleAllocationProcessRepo = new(primarymarketmocks.SettleAllocationProcessRepositoryMock)
	MockSettlementRepo = new(settlementmocks.SettlementRepositoryMock)
	MockCancelAllocationProcessRepo = new(primarymarketmocks.CancelAllocationProcessRepositoryMock)
	MockHistoricalPositionRecordRepo = new(registrymocks.HistoricalPositionRecordRepositoryMock)
	MockAssignAssetToSettlementHubProcessRepo = new(settlementmocks.AssignAssetToSettlementHubProcessRepositoryMock)
	MockCreateSettlementInstructionProcessRepo = new(settlementmocks.CreateSettlementInstructionProcessRepositoryMock)
	MockCreateSettlementTransactionProcessRepo = new(settlementmocks.CreateSettlementTransactionProcessRepositoryMock)
	MockExecuteInstructionExpirationProcessRepo = new(settlementmocks.ExecuteInstructionExpirationProcessRepositoryMock)
	MockExecuteInstructionCancellationProcessRepo = new(settlementmocks.ExecuteInstructionCancellationProcessRepositoryMock)
	MockCancelSubscriptionProcessRepo = new(primarymarketmocks.CancelSubscriptionProcessRepositoryMock)
	MockExecuteSettlementProcessRepo = new(settlementmocks.ExecuteSettlementProcessRepositoryMock)
	MockSettlementExecutionRepo = new(settlementmocks.SettlementExecutionRepositoryMock)
	MockCreateCancellationInstructionProcessRepo = new(settlementmocks.CreateCancellationInstructionProcessRepositoryMock)
	CreateSettlementTransactionProcessFactory = testcreatesettlementtransactionprocessfactory.NewCreateSettlementTransactionProcessTestFactory(MockCreateSettlementTransactionProcessRepo)
	ExecuteInstructionExpirationProcessFactory = testexecuteinstructionexpirationfactory.NewExecuteInstructionExpirationProcessTestFactory(MockExecuteInstructionExpirationProcessRepo)
	ExecuteInstructionCancellationProcessFactory = testexecuteinstructioncancellationfactory.NewExecuteInstructionCancellationProcessTestFactory(MockExecuteInstructionCancellationProcessRepo)
	CancelSubscriptionProcessFactory = testcancelsubscriptionfactory.NewCancelSubscriptionProcessTestFactory(MockCancelSubscriptionProcessRepo)
	ExecuteSettlementProcessFactory = testexecutesettlementprocessfactory.NewExecuteSettlementProcessTestFactory(MockExecuteSettlementProcessRepo)
	SettlementExecutionFactory = testsettlementexecutionfactory.NewSettlementExecutionTestFactory(MockSettlementExecutionRepo)
	MockSettlementInstructionRepo = new(settlementmocks.SettlementInstructionRepositoryMock)
	MockMetadataInstructionRepo = new(settlementmocks.MetadataInstructionRepositoryMock)
	SettlementInstructionFactory = testsettlementinstructionfactory.NewSettlementInstructionTestFactory(MockSettlementInstructionRepo)
	MockSettlementInstructionExists = new(servicemocksettlementinstruction.ExistsMock)
	MockSettlementTransactionRepo = new(settlementmocks.SettlementTransactionRepositoryMock)
	MockInstructionRepo = new(settlementmocks.InstructionRepositoryMock)
	MockApprovalProcess = new(sharedmocks.ApprovalProcessRepositoryMock)
	MockCreateComplianceEligibilityExternalListProcessRepo = new(compliancemocks.CreateComplianceEligibilityExternalListProcessRepositoryMock)
	MockMatchingProcessRepo = new(settlementmocks.MatchingProcessRepositoryMock)
	// HoldingsAssetFactory = testholdingsassetfactory.NewHoldingsAssetTestFactory(MockHoldingsAssetRepo)
	SettlementHubAssetFactory = testsettlementhubassetfactory.NewSettlementHubAssetTestFactory(MockSettlementHubAssetRepo)
	ApprovalFactory = testsharedapprovalfactory.NewApprovalTestFactory(MockApprovalProcess)
	// ComplianceEligibilityAccountFactory = testcomplianceeligibilityaccountprocessfactory.NewComplianceEligibilityAccountTestFactory(MockComplianceEligibilityAccountRepo)
	MockAddComplianceEligibilityExternalListAccountProcessRepo = new(compliancemocks.AddComplianceEligibilityExternalListAccountProcessRepositoryMock)
	MockComplianceEligibilityExternalListAccountRepo = new(compliancemocks.ComplianceEligibilityExternalListAccountRepositoryMock)
	MockComplianceEligibilityExternalListRepo = new(compliancemocks.ComplianceEligibilityExternalListRepositoryMock)
	MockRemoveComplianceEligibilityExternalListAccountProcessRepo = new(compliancemocks.RemoveComplianceEligibilityExternalListAccountProcessRepositoryMock)
	ComplianceEligibilityExternalListAccountFactory = testcomplianceeligibilityexternallistaccountfactory.NewComplianceEligibilityExternalListAccountTestFactory(MockComplianceEligibilityExternalListAccountRepo)
	HoldFactory = testholdfactory.NewHoldTestFactory(MockHoldRepo)
	MockCreateHoldProcessRepo = new(registrymocks.CreateHoldProcessRepositoryMock)
	MockExecuteHoldProcessRepo = new(registrymocks.ExecuteHoldProcessRepositoryMock)
	// MockAssetComplianceEligibilityExternalListRepo = new(issuancemocks.AssetComplianceEligibilityExternalListRepositoryMock)
	// AssetComplianceEligibilityExternalListFactory = testassetcomplianceeligibilityexternallistfactory.NewComplianceEligibilityExternalListTestFactory(MockAssetComplianceEligibilityExternalListRepo)
	MockSharedAssetComplianceEligibilityExternalListRepo = new(sharedmocks.AssetComplianceEligibilityExternalListRepositoryMock)
	MockSharedComplianceEligibilityAccountRepo = new(sharedmocks.ComplianceEligibilityAccountRepositoryMock)
	MockSharedComplianceEligibilityExternalListAccountRepo = new(sharedmocks.ComplianceEligibilityExternalListAccountRepositoryMock)
	MockSharedComplianceEligibilityExternalListRepo = new(sharedmocks.ComplianceEligibilityExternalListRepositoryMock)
	SharedAssetComplianceEligibilityExternalListFactory = testsharedassetcomplianceeligibilityexternallistfactory.NewComplianceEligibilityExternalListTestFactory(MockSharedAssetComplianceEligibilityExternalListRepo)
	MockReclaimHoldProcessRepo = new(registrymocks.ReclaimHoldProcessRepositoryMock)
	MockReleaseHoldProcessRepo = new(registrymocks.ReleaseHoldProcessRepositoryMock)
	MockSharedAssetRepo = new(sharedmocks.AssetRepositoryMock)
	MockSharedAssetClassRepo = new(sharedmocks.AssetClassRepositoryMock)
	MockSharedCapabilityRepo = new(sharedmocks.CapabilityRepositoryMock)
}

func CaptureEventHook(t *testing.T, targetEvent *event.Event) func(args mock.Arguments) {
	return func(args mock.Arguments) {
		evt, ok := args.Get(1).(event.Event)
		if !ok {
			t.Fatalf("Argument passed to EventBus.Publish was not an event.Event: %T", args.Get(1))
		}
		*targetEvent = evt
	}
}

func SetDefaultNetwork(networkId string, dlt string) {
	if config.AppConfig == nil {
		config.AppConfig = &config.Config{
			DltIngress: config.DltIngress{
				Networks: []*config.NetworkConfig{{Id: networkId, Dlt: dlt}},
			},
		}
	} else {
		config.AppConfig.DltIngress.Networks[0].Id = networkId
		config.AppConfig.DltIngress.Networks[0].Dlt = dlt
	}
}
