// Command genhttpendpoint generates the HttpEndpoint interface methods
// (Path/Feature/GinHandler) for every HTTP endpoint adapter in the bounded contexts
// listed in cmdcore.HANDLER_GEN_BCS, so they don't have to be hand-written. For each package that declares
// `type Endpoint` with a `UrlPath` const and a `Handle` or `Listen` method, it writes a
// <prefix>_http_adapter_gen.go next to the adapter.
//
// The declarations it looks for may live in a hand-written file or in a _gen.go file
// produced by another generator (e.g. genbaseprocess, whose adapter/port skeletons declare
// Endpoint/UrlPath/Handle without the HttpEndpoint methods). Only its own previous output
// (identified by the "Code generated by genhttpendpoint" header) is skipped, so re-running
// this generator doesn't reprocess its own files.
//
// Run it like the other generators, from src/main/:
//
//	go run ./../cmd/genhttpendpoint
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"dlt-ingress/src/cmd/core"
)

var tmpl *template.Template
var completedOk = false

func init() {
	var err error
	tmpl, err = template.ParseFiles("./../cmd/genhttpendpoint/method.tmpl")
	if err != nil {
		fmt.Println("❌ Failed to load template:", err)
		os.Exit(1)
	}
}

func starting() {
	fmt.Println("──────────────────────────────────────")
	fmt.Println("🌐 Starting httpendpoint generator")
	fmt.Println("──────────────────────────────────────")
}

func ending() {
	fmt.Println("───────────────────────────────")
	if completedOk {
		fmt.Println("✅ HttpEndpoint generation finished successfully")
	} else {
		fmt.Println("❌ HttpEndpoint generation failed")
	}
	fmt.Println("───────────────────────────────")
}

func main() {
	starting()
	defer ending()

	dirs := map[string]bool{}
	for _, bc := range cmdcore.HANDLER_GEN_BCS {
		root := "./../main/" + bc + "/"
		err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			dirs[filepath.Dir(path)] = true
			return nil
		})
		if err != nil {
			fmt.Println("❌ Error:", err)
			os.Exit(1)
		}
	}

	for dir := range dirs {
		if perr := processDir(dir); perr != nil {
			fmt.Println("❌ Error:", perr)
			os.Exit(1)
		}
	}
	completedOk = true
}

// endpointInfo is what we learn about a package by scanning its files.
type endpointInfo struct {
	pkg         string
	hasEndpoint bool
	hasURLPath  bool
	hasFeature  bool
	handler     string // "Handle" or "Listen"
	adapterFile string // file declaring the handler method (drives the _gen.go name)
}

func recvIsEndpoint(fd *ast.FuncDecl) bool {
	if fd.Recv == nil || len(fd.Recv.List) == 0 {
		return false
	}
	t := fd.Recv.List[0].Type
	if star, ok := t.(*ast.StarExpr); ok {
		t = star.X
	}
	id, ok := t.(*ast.Ident)
	return ok && id.Name == "Endpoint"
}

func hasConst(f *ast.File, name string) bool {
	for _, d := range f.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, s := range gd.Specs {
			vs, ok := s.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, n := range vs.Names {
				if n.Name == name {
					return true
				}
			}
		}
	}
	return false
}

func processDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	info := endpointInfo{}

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		path := filepath.Join(dir, name)
		if strings.HasSuffix(name, "_gen.go") && isOwnOutput(path) {
			// Skip our own previously generated file, but not _gen.go files from other
			// generators (e.g. genbaseprocess) — those may hold the Endpoint/UrlPath/Handle
			// declarations we need to generate HttpEndpoint methods for.
			continue
		}
		f, perr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if perr != nil {
			return perr
		}
		info.pkg = f.Name.Name

		if hasConst(f, "UrlPath") {
			info.hasURLPath = true
		}
		if hasConst(f, "Feature") {
			info.hasFeature = true
		}
		for _, d := range f.Decls {
			switch decl := d.(type) {
			case *ast.GenDecl:
				if decl.Tok != token.TYPE {
					continue
				}
				for _, s := range decl.Specs {
					ts, ok := s.(*ast.TypeSpec)
					if ok && ts.Name.Name == "Endpoint" {
						if _, ok := ts.Type.(*ast.StructType); ok {
							info.hasEndpoint = true
						}
					}
				}
			case *ast.FuncDecl:
				if recvIsEndpoint(decl) && (decl.Name.Name == "Handle" || decl.Name.Name == "Listen") {
					info.handler = decl.Name.Name
					info.adapterFile = path
				}
			}
		}
	}

	// Only generate for real HTTP endpoints.
	if !info.hasEndpoint || !info.hasURLPath || info.handler == "" {
		return nil
	}

	feature := `""`
	if info.hasFeature {
		feature = "Feature"
	}

	prefix := genPrefix(info.adapterFile)
	genPath := filepath.Join(dir, prefix+"_http_adapter_gen.go")
	if genPath == info.adapterFile {
		// The source declarations live in a _gen.go file from another generator that
		// already occupies this name (e.g. genbaseprocess's <prefix>_http_adapter_gen.go).
		// Use a distinct name so we don't overwrite it.
		genPath = filepath.Join(dir, prefix+"_http_endpoint_gen.go")
	}
	fmt.Println("⚙️  Generating:", genPath)

	var buf bytes.Buffer
	if terr := tmpl.Execute(&buf, struct {
		Package string
		Feature string
		Handler string
	}{Package: info.pkg, Feature: feature, Handler: info.handler}); terr != nil {
		return terr
	}
	formatted, ferr := format.Source(buf.Bytes())
	if ferr != nil {
		return fmt.Errorf("%s: gofmt: %w", genPath, ferr)
	}
	return os.WriteFile(genPath, formatted, 0o644)
}

// genPrefix turns ".../get_capability_http_adapter.go" into "get_capability", and
// ".../get_process_http_adapter_gen.go" (a _gen.go file from another generator) into
// "get_process" too. Falls back to the base name without ".go"/"_gen.go" otherwise.
func genPrefix(adapterFile string) string {
	base := filepath.Base(adapterFile)
	for _, suffix := range []string{"_http_adapter_gen.go", "_http_adapter.go", "_gen.go", ".go"} {
		if trimmed, ok := strings.CutSuffix(base, suffix); ok {
			return trimmed
		}
	}
	return base
}

// isOwnOutput reports whether path was generated by this tool, identified by its
// "Code generated by genhttpendpoint" header, so a re-run doesn't reprocess it.
func isOwnOutput(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	firstLine, _, _ := bytes.Cut(data, []byte("\n"))
	return bytes.Contains(firstLine, []byte("Code generated by genhttpendpoint"))
}
