[package]
name = "common"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
name = "common"

[features]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "1.0.2" }
spl-token-2022-interface = "=3.0.1"
bytemuck = { version = "1.17", features = ["derive", "min_const_generics"] }
solana-keccak-hasher = { version = ">=3.0.0, <4.0.0", features = ["sha3"] }
solana-system-interface = ">=2.0.0"


[dev-dependencies]
deploy           = { path = "../deploy",           features = ["cpi"] }
deactivate       = { path = "../deactivate",       features = ["cpi"] }
mint             = { path = "../mint",             features = ["cpi"] }
operations       = { path = "../operations",       features = ["cpi"] }
freeze           = { path = "../freeze",           features = ["cpi"] }
metadata-update  = { path = "../metadata-update",  features = ["cpi"] }
pause            = { path = "../pause",            features = ["cpi"] }
transfer-control = { path = "../transfer-control", features = ["cpi"] }
transfer         = { path = "../transfer",         features = ["cpi"] }
transfer-hook    = { path = "../transfer-hook",    features = ["cpi"] }
snapshot         = { path = "../snapshot",         features = ["cpi"] }
bond             = { path = "../bond",             features = ["cpi"] }
coupon           = { path = "../coupon",           features = ["cpi"] }
treasury         = { path = "../treasury",         features = ["cpi"] }
factory          = { path = "../factory",          features = ["cpi"] }
access-control   = { path = "../access-control",   features = ["cpi"] }
cap              = { path = "../cap",              features = ["cpi"] }
document         = { path = "../document",         features = ["cpi"] }
hold             = { path = "../hold",             features = ["cpi"] }

[lints.rust]
unexpected_cfgs = { level = "allow" }
