// Code generated by genlistener. DO NOT EDIT.

package transitfailedtransactiontoretriedlistener

import "gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/event"

func (l *Listener) EventType() string { return "transaction.RetriedEvent" }

func (l *Listener) Name() string { return "transitfailedtransactiontoretriedlistener.Listener" }

func (l *Listener) AsListener() event.Listener {
	return event.NewBaseListener(l.Listen)
}
