// Code generated by genqueryname. DO NOT EDIT.

package getcustodykey

func (q Query) QueryName() string {
	return "dlt-ingress/src/main/dltingress/app/query/getcustodykey.Query"
}

func (q Query) ResponseType() Response { var r Response; return r }
