// Code generated by genqueryname. DO NOT EDIT.

package getfailedtransactions

func (q Query) QueryName() string {
	return "dlt-ingress/src/main/dltingress/app/query/getfailedtransactions.Query"
}

func (q Query) ResponseType() Response { var r Response; return r }
