// Code generated by gencommandname. DO NOT EDIT.

package createfaucetwallet

func (c *Command) CommandName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/command/createfaucetwallet.Command"
}
