// Code generated by gencommandname. DO NOT EDIT.

package retryevmtransaction

func (c *Command) CommandName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/command/retryevmtransaction.Command"
}
