// Code generated by genrepositories. DO NOT EDIT.

package dltrolerepo

import (
	"context"
	"dlt-ingress/src/main/core/domain/role/dltrole"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/db"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	coredomainerrors "gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/domain/domainerrors"
)

// Creates a new DltRole into the database.
func (r *PostgresAssetDltRoleRepository) Create(ctx context.Context, entity *dltrole.DltRole) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to create DltRole: %v", result.Error)
	}
	return nil
}

// Save inserts or updates a new DltRole into the database.
func (r *PostgresAssetDltRoleRepository) Save(ctx context.Context, entity *dltrole.DltRole) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to insert DltRole: %v", result.Error)
	}
	return nil
}

// Delete a DltRole from the database.
func (r *PostgresAssetDltRoleRepository) Delete(ctx context.Context, entity *dltrole.DltRole) error {
	result := r.getDB(ctx).Delete(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to delete DltRole: %v", result.Error)
	}
	return nil
}

// FindById returns the DltRole with the given id.
func (r *PostgresAssetDltRoleRepository) FindById(ctx context.Context, id uuid.UUID) (*dltrole.DltRole, error) {
	var entity dltrole.DltRole
	result := r.getDB(ctx).First(&entity, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, coredomainerrors.NewEntityNotFoundDomainError("DltRole", id)
		}
		return nil, fmt.Errorf("failed to retrieve DltRole: %w", result.Error)
	}
	return &entity, nil
}

// ExistById checks if the CreateSettlementInstructionProcess with the given id exists.
func (r *PostgresAssetDltRoleRepository) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	var exists bool
	err := r.getDB(ctx).
		Model(&dltrole.DltRole{}).
		Select("count(*) > 0").
		Where("id = ?", id).
		Find(&exists).
		Error
	if err != nil {
		return false, fmt.Errorf("failed to check existence of DltRole: %w", err)
	}
	return exists, nil
}

// FindByIdPreload returns the DltRole with the given id and all associated entities.
func (r *PostgresAssetDltRoleRepository) FindByIdPreload(ctx context.Context, id uuid.UUID) (*dltrole.DltRole, error) {
	var entity dltrole.DltRole
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).First(&entity, id)

	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, coredomainerrors.NewEntityNotFoundDomainError("DltRole", id)
		}
		return nil, fmt.Errorf("failed to retrieve DltRole: %w", result.Error)
	}
	return &entity, nil
}

func recursivePreload(d *gorm.DB, level int) *gorm.DB {
	if level <= 0 {
		return d
	}
	return d.Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, level-1)
	})
}

// FindAll returns all entities DltRole in the database.
func (r *PostgresAssetDltRoleRepository) FindAll(ctx context.Context) ([]dltrole.DltRole, error) {
	var entities []dltrole.DltRole
	result := r.getDB(ctx).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch DltRole entities: %w", result.Error)
	}
	return entities, nil
}

// FindAll returns all entities DltRole in the database including deleted.
func (r *PostgresAssetDltRoleRepository) FindAllWithDeleted(ctx context.Context) ([]dltrole.DltRole, error) {
	var entities []dltrole.DltRole
	result := r.getDB(ctx).Unscoped().Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch DltRole entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPreload returns all entities DltRole in the database with all associated entities.
func (r *PostgresAssetDltRoleRepository) FindAllPreload(ctx context.Context) ([]dltrole.DltRole, error) {
	var entities []dltrole.DltRole
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch DltRole entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginated returns all entities DltRole in the database, paginated.
func (r *PostgresAssetDltRoleRepository) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]dltrole.DltRole, error) {
	var entities []dltrole.DltRole
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch DltRole entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginatedPreload returns all entities DltRole in the database with all associated entities, paginated.
func (r *PostgresAssetDltRoleRepository) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]dltrole.DltRole, error) {
	var entities []dltrole.DltRole
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch DltRole entities: %w", result.Error)
	}
	return entities, nil
}

// CountAll returns the number of entities DltRole in the database.
func (r *PostgresAssetDltRoleRepository) CountAll(ctx context.Context) (int, error) {
	var count int64
	result := r.getDB(ctx).Model(&dltrole.DltRole{}).Count(&count)
	if result.Error != nil {
		return 0, fmt.Errorf("failed to count DltRole entities: %w", result.Error)
	}
	return int(count), nil
}

func (r *PostgresAssetDltRoleRepository) getDB(ctx context.Context) *gorm.DB {
	val := r.tm.TransactionValue(ctx)
	if val == nil {
		return r.db
	}

	wrapper, ok := val.(db.GormTransaction)
	if !ok {
		return r.db
	}

	wrapperTx := wrapper.Tx
	txDb, errTx := wrapperTx.DB()
	repoDb, errDb := r.db.DB()

	if errTx == nil && errDb == nil && txDb == repoDb {
		return wrapperTx
	}

	return r.db
}
