// Code generated by gencrosscommandname. DO NOT EDIT.

package buildtransactioncross

func (c *CrossCommand) CrossCommandName() string {
	return "dlt-ingress/src/main/dltingress/port/crosscommand/buildtransaction.CrossCommand"
}
