// Code generated by gencommandname. DO NOT EDIT.

package retrysvmtransaction

func (c *Command) CommandName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/command/retrysvmtransaction.Command"
}
