// Code generated by genrepositoriesold. DO NOT EDIT.

package failedtransactionrepo

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/transaction/failedtransaction"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/db"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/domain/domainerrors"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Creates a new FailedTransaction into the database.
func (r *PostgresFailedTransactionRepository) Create(ctx context.Context, entity *failedtransaction.FailedTransaction) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to create FailedTransaction: %w", result.Error)
	}
	return nil
}

// Save inserts or updates a new FailedTransaction into the database.
func (r *PostgresFailedTransactionRepository) Save(ctx context.Context, entity *failedtransaction.FailedTransaction) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to insert FailedTransaction: %w", result.Error)
	}
	return nil
}

// Delete a FailedTransaction from the database.
func (r *PostgresFailedTransactionRepository) Delete(ctx context.Context, entity *failedtransaction.FailedTransaction) error {
	result := r.getDB(ctx).Delete(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to delete FailedTransaction: %w", result.Error)
	}
	return nil
}

// FindById returns the FailedTransaction with the given id.
func (r *PostgresFailedTransactionRepository) FindById(ctx context.Context, id uuid.UUID) (*failedtransaction.FailedTransaction, error) {
	var entity failedtransaction.FailedTransaction
	result := r.getDB(ctx).First(&entity, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("FailedTransaction", id)
		}
		return nil, fmt.Errorf("failed to retrieve FailedTransaction: %w", result.Error)
	}
	return &entity, nil
}

// ExistById checks if the FailedTransaction with the given id exists.
func (r *PostgresFailedTransactionRepository) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	var res int
	err := r.getDB(ctx).
		Model(&failedtransaction.FailedTransaction{}).
		Select("1").
		Where("id = ?", id).
		Take(&res).
		Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, nil
		}
		return false, fmt.Errorf("failed to check existence of FailedTransaction: %w", err)
	}
	return true, nil
}

// FindByIdPreload returns the FailedTransaction with the given id and all associated entities.
func (r *PostgresFailedTransactionRepository) FindByIdPreload(ctx context.Context, id uuid.UUID) (*failedtransaction.FailedTransaction, error) {
	var entity failedtransaction.FailedTransaction
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).First(&entity, id)

	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("FailedTransaction", id)
		}
		return nil, fmt.Errorf("failed to retrieve FailedTransaction: %w", result.Error)
	}
	return &entity, nil
}

func recursivePreload(d *gorm.DB, level int) *gorm.DB {
	if level <= 0 {
		return d
	}
	return d.Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, level-1)
	})
}

// FindAll returns all entities FailedTransaction in the database.
func (r *PostgresFailedTransactionRepository) FindAll(ctx context.Context) ([]failedtransaction.FailedTransaction, error) {
	var entities []failedtransaction.FailedTransaction
	result := r.getDB(ctx).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch FailedTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAll returns all entities FailedTransaction in the database including deleted.
func (r *PostgresFailedTransactionRepository) FindAllWithDeleted(ctx context.Context) ([]failedtransaction.FailedTransaction, error) {
	var entities []failedtransaction.FailedTransaction
	result := r.getDB(ctx).Unscoped().Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch FailedTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPreload returns all entities FailedTransaction in the database with all associated entities.
func (r *PostgresFailedTransactionRepository) FindAllPreload(ctx context.Context) ([]failedtransaction.FailedTransaction, error) {
	var entities []failedtransaction.FailedTransaction
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch FailedTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginated returns all entities FailedTransaction in the database, paginated.
func (r *PostgresFailedTransactionRepository) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]failedtransaction.FailedTransaction, error) {
	var entities []failedtransaction.FailedTransaction
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch FailedTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginatedPreload returns all entities FailedTransaction in the database with all associated entities, paginated.
func (r *PostgresFailedTransactionRepository) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]failedtransaction.FailedTransaction, error) {
	var entities []failedtransaction.FailedTransaction
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch FailedTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// CountAll returns the number of entities FailedTransaction in the database.
func (r *PostgresFailedTransactionRepository) CountAll(ctx context.Context) (int, error) {
	var count int64
	result := r.getDB(ctx).Model(&failedtransaction.FailedTransaction{}).Count(&count)
	if result.Error != nil {
		return 0, fmt.Errorf("failed to count FailedTransaction entities: %w", result.Error)
	}
	return int(count), nil
}

func (r *PostgresFailedTransactionRepository) getDB(ctx context.Context) *gorm.DB {
	val := r.tm.TransactionValue(ctx)
	if val == nil {
		return r.db
	}

	wrapper, ok := val.(db.GormTransaction)
	if !ok {
		return r.db
	}

	wrapperTx := wrapper.Tx
	txDb, errTx := wrapperTx.DB()
	repoDb, errDb := r.db.DB()

	if errTx == nil && errDb == nil && txDb == repoDb {
		return wrapperTx
	}

	return r.db
}
