// Code generated by genrepositoriesold. DO NOT EDIT.

package svmtransactionrepo

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/transaction/svmtransaction"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/db"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/domain/domainerrors"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Creates a new SvmTransaction into the database.
func (r *PostgresSVMTransactionRepository) Create(ctx context.Context, entity *svmtransaction.SvmTransaction) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to create SvmTransaction: %w", result.Error)
	}
	return nil
}

// Save inserts or updates a new SvmTransaction into the database.
func (r *PostgresSVMTransactionRepository) Save(ctx context.Context, entity *svmtransaction.SvmTransaction) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to insert SvmTransaction: %w", result.Error)
	}
	return nil
}

// Delete a SvmTransaction from the database.
func (r *PostgresSVMTransactionRepository) Delete(ctx context.Context, entity *svmtransaction.SvmTransaction) error {
	result := r.getDB(ctx).Delete(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to delete SvmTransaction: %w", result.Error)
	}
	return nil
}

// FindById returns the SvmTransaction with the given id.
func (r *PostgresSVMTransactionRepository) FindById(ctx context.Context, id uuid.UUID) (*svmtransaction.SvmTransaction, error) {
	var entity svmtransaction.SvmTransaction
	result := r.getDB(ctx).First(&entity, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("SvmTransaction", id)
		}
		return nil, fmt.Errorf("failed to retrieve SvmTransaction: %w", result.Error)
	}
	return &entity, nil
}

// ExistById checks if the SvmTransaction with the given id exists.
func (r *PostgresSVMTransactionRepository) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	var res int
	err := r.getDB(ctx).
		Model(&svmtransaction.SvmTransaction{}).
		Select("1").
		Where("id = ?", id).
		Take(&res).
		Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, nil
		}
		return false, fmt.Errorf("failed to check existence of SvmTransaction: %w", err)
	}
	return true, nil
}

// FindByIdPreload returns the SvmTransaction with the given id and all associated entities.
func (r *PostgresSVMTransactionRepository) FindByIdPreload(ctx context.Context, id uuid.UUID) (*svmtransaction.SvmTransaction, error) {
	var entity svmtransaction.SvmTransaction
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).First(&entity, id)

	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("SvmTransaction", id)
		}
		return nil, fmt.Errorf("failed to retrieve SvmTransaction: %w", result.Error)
	}
	return &entity, nil
}

func recursivePreload(d *gorm.DB, level int) *gorm.DB {
	if level <= 0 {
		return d
	}
	return d.Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, level-1)
	})
}

// FindAll returns all entities SvmTransaction in the database.
func (r *PostgresSVMTransactionRepository) FindAll(ctx context.Context) ([]svmtransaction.SvmTransaction, error) {
	var entities []svmtransaction.SvmTransaction
	result := r.getDB(ctx).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch SvmTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAll returns all entities SvmTransaction in the database including deleted.
func (r *PostgresSVMTransactionRepository) FindAllWithDeleted(ctx context.Context) ([]svmtransaction.SvmTransaction, error) {
	var entities []svmtransaction.SvmTransaction
	result := r.getDB(ctx).Unscoped().Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch SvmTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPreload returns all entities SvmTransaction in the database with all associated entities.
func (r *PostgresSVMTransactionRepository) FindAllPreload(ctx context.Context) ([]svmtransaction.SvmTransaction, error) {
	var entities []svmtransaction.SvmTransaction
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch SvmTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginated returns all entities SvmTransaction in the database, paginated.
func (r *PostgresSVMTransactionRepository) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]svmtransaction.SvmTransaction, error) {
	var entities []svmtransaction.SvmTransaction
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch SvmTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginatedPreload returns all entities SvmTransaction in the database with all associated entities, paginated.
func (r *PostgresSVMTransactionRepository) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]svmtransaction.SvmTransaction, error) {
	var entities []svmtransaction.SvmTransaction
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch SvmTransaction entities: %w", result.Error)
	}
	return entities, nil
}

// CountAll returns the number of entities SvmTransaction in the database.
func (r *PostgresSVMTransactionRepository) CountAll(ctx context.Context) (int, error) {
	var count int64
	result := r.getDB(ctx).Model(&svmtransaction.SvmTransaction{}).Count(&count)
	if result.Error != nil {
		return 0, fmt.Errorf("failed to count SvmTransaction entities: %w", result.Error)
	}
	return int(count), nil
}

func (r *PostgresSVMTransactionRepository) getDB(ctx context.Context) *gorm.DB {
	val := r.tm.TransactionValue(ctx)
	if val == nil {
		return r.db
	}

	wrapper, ok := val.(db.GormTransaction)
	if !ok {
		return r.db
	}

	wrapperTx := wrapper.Tx
	txDb, errTx := wrapperTx.DB()
	repoDb, errDb := r.db.DB()

	if errTx == nil && errDb == nil && txDb == repoDb {
		return wrapperTx
	}

	return r.db
}
