// Code generated by genqueryname. DO NOT EDIT.

package gettransaction

func (q Query) QueryName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/query/gettransaction.Query"
}

func (q Query) ResponseType() Response { var r Response; return r }
