// Code generated by genrepositoriesold. DO NOT EDIT.

package noncerepo

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/nonce"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/db"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/domain/domainerrors"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Creates a new Nonce into the database.
func (r *PostgresNonceRepository) Create(ctx context.Context, entity *nonce.Nonce) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to create Nonce: %w", result.Error)
	}
	return nil
}

// Save inserts or updates a new Nonce into the database.
func (r *PostgresNonceRepository) Save(ctx context.Context, entity *nonce.Nonce) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to insert Nonce: %w", result.Error)
	}
	return nil
}

// Delete a Nonce from the database.
func (r *PostgresNonceRepository) Delete(ctx context.Context, entity *nonce.Nonce) error {
	result := r.getDB(ctx).Delete(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to delete Nonce: %w", result.Error)
	}
	return nil
}

// FindById returns the Nonce with the given id.
func (r *PostgresNonceRepository) FindById(ctx context.Context, id uuid.UUID) (*nonce.Nonce, error) {
	var entity nonce.Nonce
	result := r.getDB(ctx).First(&entity, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("Nonce", id)
		}
		return nil, fmt.Errorf("failed to retrieve Nonce: %w", result.Error)
	}
	return &entity, nil
}

// ExistById checks if the Nonce with the given id exists.
func (r *PostgresNonceRepository) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	var res int
	err := r.getDB(ctx).
		Model(&nonce.Nonce{}).
		Select("1").
		Where("id = ?", id).
		Take(&res).
		Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, nil
		}
		return false, fmt.Errorf("failed to check existence of Nonce: %w", err)
	}
	return true, nil
}

// FindByIdPreload returns the Nonce with the given id and all associated entities.
func (r *PostgresNonceRepository) FindByIdPreload(ctx context.Context, id uuid.UUID) (*nonce.Nonce, error) {
	var entity nonce.Nonce
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).First(&entity, id)

	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("Nonce", id)
		}
		return nil, fmt.Errorf("failed to retrieve Nonce: %w", result.Error)
	}
	return &entity, nil
}

func recursivePreload(d *gorm.DB, level int) *gorm.DB {
	if level <= 0 {
		return d
	}
	return d.Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, level-1)
	})
}

// FindAll returns all entities Nonce in the database.
func (r *PostgresNonceRepository) FindAll(ctx context.Context) ([]nonce.Nonce, error) {
	var entities []nonce.Nonce
	result := r.getDB(ctx).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch Nonce entities: %w", result.Error)
	}
	return entities, nil
}

// FindAll returns all entities Nonce in the database including deleted.
func (r *PostgresNonceRepository) FindAllWithDeleted(ctx context.Context) ([]nonce.Nonce, error) {
	var entities []nonce.Nonce
	result := r.getDB(ctx).Unscoped().Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch Nonce entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPreload returns all entities Nonce in the database with all associated entities.
func (r *PostgresNonceRepository) FindAllPreload(ctx context.Context) ([]nonce.Nonce, error) {
	var entities []nonce.Nonce
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch Nonce entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginated returns all entities Nonce in the database, paginated.
func (r *PostgresNonceRepository) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]nonce.Nonce, error) {
	var entities []nonce.Nonce
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch Nonce entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginatedPreload returns all entities Nonce in the database with all associated entities, paginated.
func (r *PostgresNonceRepository) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]nonce.Nonce, error) {
	var entities []nonce.Nonce
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch Nonce entities: %w", result.Error)
	}
	return entities, nil
}

// CountAll returns the number of entities Nonce in the database.
func (r *PostgresNonceRepository) CountAll(ctx context.Context) (int, error) {
	var count int64
	result := r.getDB(ctx).Model(&nonce.Nonce{}).Count(&count)
	if result.Error != nil {
		return 0, fmt.Errorf("failed to count Nonce entities: %w", result.Error)
	}
	return int(count), nil
}

func (r *PostgresNonceRepository) getDB(ctx context.Context) *gorm.DB {
	val := r.tm.TransactionValue(ctx)
	if val == nil {
		return r.db
	}

	wrapper, ok := val.(db.GormTransaction)
	if !ok {
		return r.db
	}

	wrapperTx := wrapper.Tx
	txDb, errTx := wrapperTx.DB()
	repoDb, errDb := r.db.DB()

	if errTx == nil && errDb == nil && txDb == repoDb {
		return wrapperTx
	}

	return r.db
}
