// Code generated by genrepositoriesold. DO NOT EDIT.

package queuelockrepo

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/queuelock"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/db"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/domain/domainerrors"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Creates a new QueueLock into the database.
func (r *PostgresQueueLockRepository) Create(ctx context.Context, entity *queuelock.QueueLock) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to create QueueLock: %w", result.Error)
	}
	return nil
}

// Save inserts or updates a new QueueLock into the database.
func (r *PostgresQueueLockRepository) Save(ctx context.Context, entity *queuelock.QueueLock) error {
	result := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to insert QueueLock: %w", result.Error)
	}
	return nil
}

// Delete a QueueLock from the database.
func (r *PostgresQueueLockRepository) Delete(ctx context.Context, entity *queuelock.QueueLock) error {
	result := r.getDB(ctx).Delete(&entity)
	if result.Error != nil {
		return fmt.Errorf("failed to delete QueueLock: %w", result.Error)
	}
	return nil
}

// FindById returns the QueueLock with the given id.
func (r *PostgresQueueLockRepository) FindById(ctx context.Context, id uuid.UUID) (*queuelock.QueueLock, error) {
	var entity queuelock.QueueLock
	result := r.getDB(ctx).First(&entity, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("QueueLock", id)
		}
		return nil, fmt.Errorf("failed to retrieve QueueLock: %w", result.Error)
	}
	return &entity, nil
}

// ExistById checks if the QueueLock with the given id exists.
func (r *PostgresQueueLockRepository) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	var res int
	err := r.getDB(ctx).
		Model(&queuelock.QueueLock{}).
		Select("1").
		Where("id = ?", id).
		Take(&res).
		Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, nil
		}
		return false, fmt.Errorf("failed to check existence of QueueLock: %w", err)
	}
	return true, nil
}

// FindByIdPreload returns the QueueLock with the given id and all associated entities.
func (r *PostgresQueueLockRepository) FindByIdPreload(ctx context.Context, id uuid.UUID) (*queuelock.QueueLock, error) {
	var entity queuelock.QueueLock
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).First(&entity, id)

	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("QueueLock", id)
		}
		return nil, fmt.Errorf("failed to retrieve QueueLock: %w", result.Error)
	}
	return &entity, nil
}

func recursivePreload(d *gorm.DB, level int) *gorm.DB {
	if level <= 0 {
		return d
	}
	return d.Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, level-1)
	})
}

// FindAll returns all entities QueueLock in the database.
func (r *PostgresQueueLockRepository) FindAll(ctx context.Context) ([]queuelock.QueueLock, error) {
	var entities []queuelock.QueueLock
	result := r.getDB(ctx).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch QueueLock entities: %w", result.Error)
	}
	return entities, nil
}

// FindAll returns all entities QueueLock in the database including deleted.
func (r *PostgresQueueLockRepository) FindAllWithDeleted(ctx context.Context) ([]queuelock.QueueLock, error) {
	var entities []queuelock.QueueLock
	result := r.getDB(ctx).Unscoped().Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch QueueLock entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPreload returns all entities QueueLock in the database with all associated entities.
func (r *PostgresQueueLockRepository) FindAllPreload(ctx context.Context) ([]queuelock.QueueLock, error) {
	var entities []queuelock.QueueLock
	result := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch QueueLock entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginated returns all entities QueueLock in the database, paginated.
func (r *PostgresQueueLockRepository) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]queuelock.QueueLock, error) {
	var entities []queuelock.QueueLock
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch QueueLock entities: %w", result.Error)
	}
	return entities, nil
}

// FindAllPaginatedPreload returns all entities QueueLock in the database with all associated entities, paginated.
func (r *PostgresQueueLockRepository) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]queuelock.QueueLock, error) {
	var entities []queuelock.QueueLock
	result := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&entities)
	if result.Error != nil {
		return entities, fmt.Errorf("failed to fetch QueueLock entities: %w", result.Error)
	}
	return entities, nil
}

// CountAll returns the number of entities QueueLock in the database.
func (r *PostgresQueueLockRepository) CountAll(ctx context.Context) (int, error) {
	var count int64
	result := r.getDB(ctx).Model(&queuelock.QueueLock{}).Count(&count)
	if result.Error != nil {
		return 0, fmt.Errorf("failed to count QueueLock entities: %w", result.Error)
	}
	return int(count), nil
}

func (r *PostgresQueueLockRepository) getDB(ctx context.Context) *gorm.DB {
	val := r.tm.TransactionValue(ctx)
	if val == nil {
		return r.db
	}

	wrapper, ok := val.(db.GormTransaction)
	if !ok {
		return r.db
	}

	wrapperTx := wrapper.Tx
	txDb, errTx := wrapperTx.DB()
	repoDb, errDb := r.db.DB()

	if errTx == nil && errDb == nil && txDb == repoDb {
		return wrapperTx
	}

	return r.db
}
