[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.14"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]

[programs.localnet]
access_control = "GpyjQqBWux3JYqxKCXFrDbWZmhFWBJWVaVivkBW2DL2w"
bond = "8opYXiWzWBrUEr5vtcvaX1ybzYaMKrndxkW1U9Patk46"
cap = "64THHYmfoHeWxbZQYq8yRsQJYydfd7yPa6MzNgebiJLm"
coupon = "CGQMgamBMtJ97CCMwVD9v5vAYVzFsXLy8beN8Ej6t3FK"
deactivate = "H2iRjVVKsKQMAnJKqiTfW2LGvT1G9tDqQ81DzRjxfX7V"
deploy = "HCe5Um7ThFBzDSyn256EPQvyr6jy6E66ydzZ5hMta3Tq"
document = "DzYjHw2JUBT8RdNqT8P5soRxJhmL6obibRUs5sMJ2Khi"
factory = "FEY9E77nH7R1gLGNxkhYKchJpB6MgpMrWMhkNXrNhzR5"
freeze = "8L1kqDvAYC9dQXNNNnZbABtRbHGjzoxSgAPzbQZmwmSd"
hold = "J8iq5Qz8tXLswZBbUFHuJukf3jpwEXLGVpvFoPZb2qY3"
metadata_update = "iShebeGRBZYSBMQYGAg8DbLnbaW2eDvX1Zt8EG9G1ZV"
mint = "BgVv7zYbf3L4ECwaeNoNqD6unKWvQtgTwRJ2Dma7iSHQ"
operations = "BHDyg8PeUyVBpmkcjYLdnt3VCmYf4wp8Xeu6TXREiLKp"
pause = "5j3F89fmVVusjwy9z3Rv5wLaVj4ovhwctQ7TRBsxNghq"
snapshot = "hgUtrpstViwxutrkoVXwQh3GQC18wHAmuAvYFTNiV2M"
transfer = "Fa5VLqopKp6cokXJreYeNNmUG8F9AaE4CUBnGQvtdq7Q"
transfer_control = "3h92PdZJB7TuCzp6iPDtrJm2k8V7fn5ETYNwCYiYy9Eo"
transfer_hook = "2qjsucJfrjP93FCwnYjc9EjYzYS8u31eWHhQo1jR9pcg"
treasury = "G71RRNtr2PLZ9Tbmp9CKnxghf3aMoasUwLGPb2u7BytA"

[programs.mainnet]

[provider]
cluster = "localnet"
wallet = "./test-wallet.json"

[workspace]
members = ["programs/deactivate", "programs/freeze", "programs/deploy", "programs/metadata-update", "programs/mint", "programs/operations", "programs/pause", "programs/snapshot", "programs/transfer", "programs/transfer-control", "programs/transfer-hook", "programs/bond", "programs/coupon", "programs/treasury", "programs/factory", "programs/access-control", "programs/cap", "programs/document", "programs/hold"]

[scripts]
test = "solana airdrop 1000 $(solana-keygen pubkey ./test-wallet.json) -u http://127.0.0.1:8899 && anchor program deploy --no-idl && ANCHOR_WALLET=./test-wallet.json NODE_OPTIONS='--import tsx' npx mocha \"tests/${TEST_FILE:-**/*}.ts\" ${TEST:+--grep \"$TEST\"}"

[hooks]

[surfpool]
startup_wait = 2000
shutdown_wait = 2000
rpc_port = 8899
ws_port = 8900
host = "127.0.0.1"
online = false
log_level = "warn"
block_production_mode = "clock"
