// Code generated by genhttpendpoint. DO NOT EDIT.

package retryevmtransaction

import (
	"github.com/gin-gonic/gin"
	coreApi "gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api"
)

func (e *Endpoint) Path() string    { return UrlPath }
func (e *Endpoint) Feature() string { return "" }
func (e *Endpoint) GinHandler() gin.HandlerFunc {
	return coreApi.NewHttpAdapter(e.Handle).Handler
}
