// Code generated by gencommandname. DO NOT EDIT.

package buildtransaction

func (c *Command) CommandName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/command/buildtransaction.Command"
}
