// Code generated by gencommandname. DO NOT EDIT.

package savefailedtransaction

func (c *Command) CommandName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/command/savefailedtransaction.Command"
}
