// Code generated by genrepositories. DO NOT EDIT.

package custodykeyrepo

import (
	"context"
	"dlt-ingress/src/main/dltingress/internal/domain/custodykey"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/db"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/domain/domainerrors"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Creates a new CustodyKey into the database.
func (r *Postgres) Create(ctx context.Context, cst *custodykey.CustodyKey) error {
	rec := FromDomain(*cst)
	if err := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(&rec).Error; err != nil {
		return fmt.Errorf("failed to create CustodyKey: %w", err)
	}
	*cst = ToDomain(rec)
	return nil
}

// Save inserts or updates a new CustodyKey into the database.
func (r *Postgres) Save(ctx context.Context, cst *custodykey.CustodyKey) error {
	rec := FromDomain(*cst)
	if err := r.getDB(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(&rec).Error; err != nil {
		return fmt.Errorf("failed to insert CustodyKey: %w", err)
	}
	*cst = ToDomain(rec)
	return nil
}

// Delete a CustodyKey from the database.
func (r *Postgres) Delete(ctx context.Context, cst *custodykey.CustodyKey) error {
	rec := FromDomain(*cst)
	if err := r.getDB(ctx).Delete(&rec).Error; err != nil {
		return fmt.Errorf("failed to delete CustodyKey: %w", err)
	}
	return nil
}

// FindById returns the CustodyKey with the given id.
func (r *Postgres) FindById(ctx context.Context, id uuid.UUID) (*custodykey.CustodyKey, error) {
	var rec CustodyKey
	if err := r.getDB(ctx).First(&rec, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("CustodyKey", id)
		}
		return nil, fmt.Errorf("failed to retrieve CustodyKey: %w", err)
	}
	cst := ToDomain(rec)
	return &cst, nil
}

// ExistById checks if the CustodyKey with the given id exists.
func (r *Postgres) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	var res int
	err := r.getDB(ctx).
		Model(&CustodyKey{}).
		Select("1").
		Where("id = ?", id).
		Take(&res).
		Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, nil
		}
		return false, fmt.Errorf("failed to check existence of CustodyKey: %w", err)
	}
	return true, nil
}

// FindByIdPreload returns the CustodyKey with the given id and all associated entities.
func (r *Postgres) FindByIdPreload(ctx context.Context, id uuid.UUID) (*custodykey.CustodyKey, error) {
	var rec CustodyKey
	if err := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).First(&rec, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domainerrors.NewEntityNotFoundDomainError("CustodyKey", id)
		}
		return nil, fmt.Errorf("failed to retrieve CustodyKey: %w", err)
	}
	cst := ToDomain(rec)
	return &cst, nil
}

func recursivePreload(d *gorm.DB, level int) *gorm.DB {
	if level <= 0 {
		return d
	}
	return d.Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, level-1)
	})
}

// FindAll returns all entities CustodyKey in the database.
func (r *Postgres) FindAll(ctx context.Context) ([]custodykey.CustodyKey, error) {
	var recs []CustodyKey
	if err := r.getDB(ctx).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch CustodyKey entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllWithDeleted returns all entities CustodyKey in the database including deleted.
func (r *Postgres) FindAllWithDeleted(ctx context.Context) ([]custodykey.CustodyKey, error) {
	var recs []CustodyKey
	if err := r.getDB(ctx).Unscoped().Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch CustodyKey entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllPreload returns all entities CustodyKey in the database with all associated entities.
func (r *Postgres) FindAllPreload(ctx context.Context) ([]custodykey.CustodyKey, error) {
	var recs []CustodyKey
	if err := r.getDB(ctx).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch CustodyKey entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllPaginated returns all entities CustodyKey in the database, paginated.
func (r *Postgres) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]custodykey.CustodyKey, error) {
	var recs []CustodyKey
	if err := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch CustodyKey entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// FindAllPaginatedPreload returns all entities CustodyKey in the database with all associated entities, paginated.
func (r *Postgres) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]custodykey.CustodyKey, error) {
	var recs []CustodyKey
	if err := r.getDB(ctx).Limit(params.PageSize).Offset(params.Offset).Order(params.OrderClause()).Preload(clause.Associations, func(db *gorm.DB) *gorm.DB {
		return recursivePreload(db, 3)
	}).Find(&recs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch CustodyKey entities: %w", err)
	}
	return ToDomainList(recs), nil
}

// CountAll returns the number of entities CustodyKey in the database.
func (r *Postgres) CountAll(ctx context.Context) (int, error) {
	var count int64
	if err := r.getDB(ctx).Model(&CustodyKey{}).Count(&count).Error; err != nil {
		return 0, fmt.Errorf("failed to count CustodyKey entities: %w", err)
	}
	return int(count), nil
}

func (r *Postgres) getDB(ctx context.Context) *gorm.DB {
	val := r.tm.TransactionValue(ctx)
	if val == nil {
		return r.db
	}

	wrapper, ok := val.(db.GormTransaction)
	if !ok {
		return r.db
	}

	wrapperTx := wrapper.Tx
	txDb, errTx := wrapperTx.DB()
	repoDb, errDb := r.db.DB()

	if errTx == nil && errDb == nil && txDb == repoDb {
		return wrapperTx
	}

	return r.db
}

var _ custodykey.Repository = (*Postgres)(nil)
