// Code generated by genrepositories. DO NOT EDIT.

package mocks

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/custodykey"
	"dlt-ingress/src/main/dltingress/port/repository/custodykey"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type CustodyKeyRepositoryMock struct {
	mock.Mock
}

func (m *CustodyKeyRepositoryMock) Create(ctx context.Context, entity *custodykey.CustodyKey) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *CustodyKeyRepositoryMock) Save(ctx context.Context, entity *custodykey.CustodyKey) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *CustodyKeyRepositoryMock) Delete(ctx context.Context, entity *custodykey.CustodyKey) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *CustodyKeyRepositoryMock) FindById(ctx context.Context, id uuid.UUID) (*custodykey.CustodyKey, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*custodykey.CustodyKey), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) FindByIdPreload(ctx context.Context, id uuid.UUID) (*custodykey.CustodyKey, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*custodykey.CustodyKey), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) FindAll(ctx context.Context) ([]custodykey.CustodyKey, error) {
	args := m.Called(ctx)
	return args.Get(0).([]custodykey.CustodyKey), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) FindAllWithDeleted(ctx context.Context) ([]custodykey.CustodyKey, error) {
	args := m.Called(ctx)
	return args.Get(0).([]custodykey.CustodyKey), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) FindAllPreload(ctx context.Context) ([]custodykey.CustodyKey, error) {
	args := m.Called(ctx)
	return args.Get(0).([]custodykey.CustodyKey), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]custodykey.CustodyKey, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]custodykey.CustodyKey), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]custodykey.CustodyKey, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]custodykey.CustodyKey), args.Error(1)
}

func (m *CustodyKeyRepositoryMock) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Get(0).(int), args.Error(1)
}

var _ custodykeyrepo.Repository = (*CustodyKeyRepositoryMock)(nil)
