// Code generated by genrepositories. DO NOT EDIT.

package mocks

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/transaction/evmtransaction"
	"dlt-ingress/src/main/dltingress/port/repository/transaction/evmtransaction"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type EvmTransactionRepositoryMock struct {
	mock.Mock
}

func (m *EvmTransactionRepositoryMock) Create(ctx context.Context, entity *evmtransaction.EvmTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *EvmTransactionRepositoryMock) Save(ctx context.Context, entity *evmtransaction.EvmTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *EvmTransactionRepositoryMock) Delete(ctx context.Context, entity *evmtransaction.EvmTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *EvmTransactionRepositoryMock) FindById(ctx context.Context, id uuid.UUID) (*evmtransaction.EvmTransaction, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*evmtransaction.EvmTransaction), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) FindByIdPreload(ctx context.Context, id uuid.UUID) (*evmtransaction.EvmTransaction, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*evmtransaction.EvmTransaction), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) FindAll(ctx context.Context) ([]evmtransaction.EvmTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]evmtransaction.EvmTransaction), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) FindAllWithDeleted(ctx context.Context) ([]evmtransaction.EvmTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]evmtransaction.EvmTransaction), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) FindAllPreload(ctx context.Context) ([]evmtransaction.EvmTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]evmtransaction.EvmTransaction), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]evmtransaction.EvmTransaction, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]evmtransaction.EvmTransaction), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]evmtransaction.EvmTransaction, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]evmtransaction.EvmTransaction), args.Error(1)
}

func (m *EvmTransactionRepositoryMock) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Get(0).(int), args.Error(1)
}

var _ evmtransactionrepo.Repository = (*EvmTransactionRepositoryMock)(nil)
