// Code generated by genrepositories. DO NOT EDIT.

package mocks

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/transaction/failedtransaction"
	"dlt-ingress/src/main/dltingress/port/repository/transaction/failedtransaction"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type FailedTransactionRepositoryMock struct {
	mock.Mock
}

func (m *FailedTransactionRepositoryMock) Create(ctx context.Context, entity *failedtransaction.FailedTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *FailedTransactionRepositoryMock) Save(ctx context.Context, entity *failedtransaction.FailedTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *FailedTransactionRepositoryMock) Delete(ctx context.Context, entity *failedtransaction.FailedTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *FailedTransactionRepositoryMock) FindById(ctx context.Context, id uuid.UUID) (*failedtransaction.FailedTransaction, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*failedtransaction.FailedTransaction), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) FindByIdPreload(ctx context.Context, id uuid.UUID) (*failedtransaction.FailedTransaction, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*failedtransaction.FailedTransaction), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) FindAll(ctx context.Context) ([]failedtransaction.FailedTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]failedtransaction.FailedTransaction), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) FindAllWithDeleted(ctx context.Context) ([]failedtransaction.FailedTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]failedtransaction.FailedTransaction), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) FindAllPreload(ctx context.Context) ([]failedtransaction.FailedTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]failedtransaction.FailedTransaction), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]failedtransaction.FailedTransaction, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]failedtransaction.FailedTransaction), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]failedtransaction.FailedTransaction, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]failedtransaction.FailedTransaction), args.Error(1)
}

func (m *FailedTransactionRepositoryMock) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Get(0).(int), args.Error(1)
}

var _ failedtransactionrepo.Repository = (*FailedTransactionRepositoryMock)(nil)
