// Code generated by genrepositories. DO NOT EDIT.

package mocks

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/nonce"
	"dlt-ingress/src/main/dltingress/port/repository/nonce"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type NonceRepositoryMock struct {
	mock.Mock
}

func (m *NonceRepositoryMock) Create(ctx context.Context, entity *nonce.Nonce) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *NonceRepositoryMock) Save(ctx context.Context, entity *nonce.Nonce) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *NonceRepositoryMock) Delete(ctx context.Context, entity *nonce.Nonce) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *NonceRepositoryMock) FindById(ctx context.Context, id uuid.UUID) (*nonce.Nonce, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*nonce.Nonce), args.Error(1)
}

func (m *NonceRepositoryMock) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *NonceRepositoryMock) FindByIdPreload(ctx context.Context, id uuid.UUID) (*nonce.Nonce, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*nonce.Nonce), args.Error(1)
}

func (m *NonceRepositoryMock) FindAll(ctx context.Context) ([]nonce.Nonce, error) {
	args := m.Called(ctx)
	return args.Get(0).([]nonce.Nonce), args.Error(1)
}

func (m *NonceRepositoryMock) FindAllWithDeleted(ctx context.Context) ([]nonce.Nonce, error) {
	args := m.Called(ctx)
	return args.Get(0).([]nonce.Nonce), args.Error(1)
}

func (m *NonceRepositoryMock) FindAllPreload(ctx context.Context) ([]nonce.Nonce, error) {
	args := m.Called(ctx)
	return args.Get(0).([]nonce.Nonce), args.Error(1)
}

func (m *NonceRepositoryMock) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]nonce.Nonce, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]nonce.Nonce), args.Error(1)
}

func (m *NonceRepositoryMock) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]nonce.Nonce, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]nonce.Nonce), args.Error(1)
}

func (m *NonceRepositoryMock) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Get(0).(int), args.Error(1)
}

var _ noncerepo.Repository = (*NonceRepositoryMock)(nil)
