// Code generated by genrepositories. DO NOT EDIT.

package mocks

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/queuelock"
	"dlt-ingress/src/main/dltingress/port/repository/queue"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type QueueLockRepositoryMock struct {
	mock.Mock
}

func (m *QueueLockRepositoryMock) Create(ctx context.Context, entity *queuelock.QueueLock) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *QueueLockRepositoryMock) Save(ctx context.Context, entity *queuelock.QueueLock) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *QueueLockRepositoryMock) Delete(ctx context.Context, entity *queuelock.QueueLock) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *QueueLockRepositoryMock) FindById(ctx context.Context, id uuid.UUID) (*queuelock.QueueLock, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*queuelock.QueueLock), args.Error(1)
}

func (m *QueueLockRepositoryMock) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *QueueLockRepositoryMock) FindByIdPreload(ctx context.Context, id uuid.UUID) (*queuelock.QueueLock, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*queuelock.QueueLock), args.Error(1)
}

func (m *QueueLockRepositoryMock) FindAll(ctx context.Context) ([]queuelock.QueueLock, error) {
	args := m.Called(ctx)
	return args.Get(0).([]queuelock.QueueLock), args.Error(1)
}

func (m *QueueLockRepositoryMock) FindAllWithDeleted(ctx context.Context) ([]queuelock.QueueLock, error) {
	args := m.Called(ctx)
	return args.Get(0).([]queuelock.QueueLock), args.Error(1)
}

func (m *QueueLockRepositoryMock) FindAllPreload(ctx context.Context) ([]queuelock.QueueLock, error) {
	args := m.Called(ctx)
	return args.Get(0).([]queuelock.QueueLock), args.Error(1)
}

func (m *QueueLockRepositoryMock) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]queuelock.QueueLock, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]queuelock.QueueLock), args.Error(1)
}

func (m *QueueLockRepositoryMock) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]queuelock.QueueLock, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]queuelock.QueueLock), args.Error(1)
}

func (m *QueueLockRepositoryMock) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Get(0).(int), args.Error(1)
}

var _ queuelockrepo.Repository = (*QueueLockRepositoryMock)(nil)
