// Code generated by genrepositories. DO NOT EDIT.

package mocks

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/transaction/svmtransaction"
	"dlt-ingress/src/main/dltingress/port/repository/transaction/svmtransactionrepo"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type SvmTransactionRepositoryMock struct {
	mock.Mock
}

func (m *SvmTransactionRepositoryMock) Create(ctx context.Context, entity *svmtransaction.SvmTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *SvmTransactionRepositoryMock) Save(ctx context.Context, entity *svmtransaction.SvmTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *SvmTransactionRepositoryMock) Delete(ctx context.Context, entity *svmtransaction.SvmTransaction) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *SvmTransactionRepositoryMock) FindById(ctx context.Context, id uuid.UUID) (*svmtransaction.SvmTransaction, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*svmtransaction.SvmTransaction), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) FindByIdPreload(ctx context.Context, id uuid.UUID) (*svmtransaction.SvmTransaction, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*svmtransaction.SvmTransaction), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) FindAll(ctx context.Context) ([]svmtransaction.SvmTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]svmtransaction.SvmTransaction), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) FindAllWithDeleted(ctx context.Context) ([]svmtransaction.SvmTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]svmtransaction.SvmTransaction), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) FindAllPreload(ctx context.Context) ([]svmtransaction.SvmTransaction, error) {
	args := m.Called(ctx)
	return args.Get(0).([]svmtransaction.SvmTransaction), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]svmtransaction.SvmTransaction, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]svmtransaction.SvmTransaction), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]svmtransaction.SvmTransaction, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]svmtransaction.SvmTransaction), args.Error(1)
}

func (m *SvmTransactionRepositoryMock) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Get(0).(int), args.Error(1)
}

var _ svmtransactionrepo.Repository = (*SvmTransactionRepositoryMock)(nil)
