// Code generated by genrepositories. DO NOT EDIT.

package mocks

import (
	"context"
	"dlt-ingress/src/main/dltingress/domain/txqueueslot"
	"dlt-ingress/src/main/dltingress/port/repository/txqueueslot"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type TxQueueSlotRepositoryMock struct {
	mock.Mock
}

func (m *TxQueueSlotRepositoryMock) Create(ctx context.Context, entity *txqueueslot.TxQueueSlot) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *TxQueueSlotRepositoryMock) Save(ctx context.Context, entity *txqueueslot.TxQueueSlot) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *TxQueueSlotRepositoryMock) Delete(ctx context.Context, entity *txqueueslot.TxQueueSlot) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *TxQueueSlotRepositoryMock) FindById(ctx context.Context, id uuid.UUID) (*txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) FindByIdPreload(ctx context.Context, id uuid.UUID) (*txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) FindAll(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx)
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) FindAllWithDeleted(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx)
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) FindAllPreload(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx)
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, params)
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *TxQueueSlotRepositoryMock) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Get(0).(int), args.Error(1)
}

var _ txqueueslotrepo.Repository = (*TxQueueSlotRepositoryMock)(nil)
