// Code generated by gencrossqueryname. DO NOT EDIT.

package contractreadcross

func (q CrossQuery) CrossQueryName() string {
	return "dlt-ingress/src/main/dltingress/port/crossquery/contractread.CrossQuery"
}

func (q CrossQuery) ResponseType() Response { var r Response; return r }
