// Code generated by gencrosscommandname. DO NOT EDIT.

package signandsendcross

func (c *CrossCommand) CrossCommandName() string {
	return "dlt-ingress/src/main/dltingress/port/command/signandsend.CrossCommand"
}
