package main

import (
	"os"
	"reflect"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/event"

	"dlt-ingress/src/main/dltingress/internal/domain/custodykey"
	"dlt-ingress/src/main/dltingress/internal/domain/transaction"
)

// Discovery walks src/main by relative path, exactly as the generator does when make runs it from
// the repository root. `go test` starts in the package directory, so move up to that root.
func TestMain(m *testing.M) {
	err := os.Chdir("../../..")
	if err != nil {
		panic(err)
	}

	os.Exit(m.Run())
}

func discoverDltingress(t *testing.T) map[string]discovered {
	t.Helper()

	scanner, err := newScanner(srcMainDir)
	require.NoError(t, err)

	found, err := scanner.discover(dltingressSpec.root())
	require.NoError(t, err)

	byType := map[string]discovered{}
	for _, ev := range found {
		byType[ev.goType] = ev
	}

	return byType
}

// A json tag on an event is the wire contract twice over: outbox rows are decoded by these names,
// and the payload schemas are reflected from them. The tag must be the field name in camelCase —
// json's decoding is case-insensitive, so rows written under the older PascalCase keys still
// decode, but the generated schema and everything reading the payload by key follow the tag. An
// untagged field is invisible to reflection and would silently vanish from the spec, so absence
// is a failure too.
func TestEventJSONTagsAreCamelCaseFieldNames(t *testing.T) {
	forEachEventField(t, func(path string, field reflect.StructField) {
		tag, ok := field.Tag.Lookup("json")
		if !ok {
			t.Errorf("%s has no json tag, so it is missing from the generated spec", path)

			return
		}

		name := strings.Split(tag, ",")[0]
		assert.Equal(t, lowerFirst(field.Name), name, "%s is serialised under another name", path)
	})
}

// The other half of the tag contract: a payload field says what it means, or the spec documents
// it as a bare type and the reader has to open the Go struct to find out — which is the whole
// thing the contract exists to avoid. A description is therefore not optional, on any field of
// any catalogued event.
func TestEventFieldsAreDescribed(t *testing.T) {
	forEachEventField(t, func(path string, field reflect.StructField) {
		description, ok := field.Tag.Lookup("description")
		if !ok {
			t.Errorf("%s has no description tag, so the generated spec documents it as a bare type", path)

			return
		}

		assert.NotEmpty(t, strings.TrimSpace(description), "%s has an empty description tag", path)
	})
}

func forEachEventField(t *testing.T, check func(path string, field reflect.StructField)) {
	t.Helper()

	for _, s := range catalog {
		for _, entry := range s.docs {
			typ := reflect.TypeOf(entry.event)

			for _, field := range payloadFields(typ, s.bc+"/"+typ.Name()) {
				check(field.path, field.StructField)
			}
		}
	}
}

// payloadFields is every field reflection turns into a property: exported, with the embedded
// transaction models flattened into the event that carries them.
func payloadFields(typ reflect.Type, path string) []payloadField {
	var fields []payloadField

	for i := range typ.NumField() {
		field := typ.Field(i)

		fieldType := field.Type
		if fieldType.Kind() == reflect.Pointer {
			fieldType = fieldType.Elem()
		}

		switch {
		// BaseEvent is upstream and untagged, which is why baseEventSchema exists and why Id
		// and CreatedAt are the two PascalCase keys left on the wire.
		case field.Anonymous && fieldType == reflect.TypeOf(event.BaseEvent{}):
		case field.Anonymous:
			fields = append(fields, payloadFields(fieldType, path+"."+field.Name)...)
		case field.IsExported():
			fields = append(fields, payloadField{StructField: field, path: path + "." + field.Name})
		}
	}

	return fields
}

type payloadField struct {
	reflect.StructField

	path string
}

// render validates the document it returns, so this covers every catalogued spec against the
// AsyncAPI meta-schema. It also asserts the determinism the CI drift gate assumes.
func TestSpecsRenderDeterministically(t *testing.T) {
	scanner, err := newScanner(srcMainDir)
	require.NoError(t, err)

	require.NotEmpty(t, catalog)

	for _, s := range catalog {
		t.Run(s.bc, func(t *testing.T) {
			first, err := scanner.generate(s)
			require.NoError(t, err)
			assert.True(t, strings.HasPrefix(string(first), "# Generated by"))

			second, err := scanner.generate(s)
			require.NoError(t, err)
			assert.Equal(t, string(first), string(second))
		})
	}
}

// What discovery reads off dltingress, asserted against what the bounded context does: eleven
// structs embed event.BaseEvent, eight of them are published, and the producer and both consumers
// of KeyCreated are found without any of them being declared anywhere.
func TestDiscoveryReadsProducersAndConsumers(t *testing.T) {
	events := discoverDltingress(t)

	assert.Len(t, events, 11)

	keyCreated := events["custodykey.KeyCreatedEvent"]
	assert.Equal(t, []string{"createkey command handler"}, keyCreated.publishers)
	assert.Equal(t, []string{"fundaccountlistener.Listener", "keycreatedlistener.Listener"}, keyCreated.consumers)
	assert.Equal(t, "custodykey", keyCreated.aggregate)
	assert.False(t, keyCreated.cross)
	assert.Contains(t, keyCreated.pos, "custody_key_events.go:")

	// Published from a listener, onto the cross bus, and consumed by nobody.
	crossEvent := events["custodykeyevents.KeyCreatedCrossEvent"]
	assert.Equal(t, []string{"keycreated listener"}, crossEvent.publishers)
	assert.True(t, crossEvent.cross)
	assert.Empty(t, crossEvent.consumers)

	// Published as a variable declared by type and assigned in a switch, not as a literal.
	assert.Equal(t,
		[]string{"signandsend command handler"},
		events["transaction.TransactionSentEvent"].publishers,
	)

	// A command response that only looks like an event.
	assert.False(t, events["transaction.TransactionBuiltEvent"].published())
}

// The gate: an event in the code with no entry in the catalog stops generation, naming the file,
// the line and the publisher, because the next thing its reader does is open that file.
func TestResolveMessagesRejectsUndocumentedEvent(t *testing.T) {
	_, err := resolveMessages(spec{bc: "dltingress"}, []discovered{{
		goType:     "transaction.SomethingHappenedEvent",
		typeName:   "SomethingHappenedEvent",
		aggregate:  "transaction",
		pos:        "src/main/dltingress/domain/transaction/transaction_events.go:42",
		publishers: []string{"dosomething command handler"},
	}})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "transaction_events.go:42")
	assert.Contains(t, err.Error(), "has no entry in catalog.go")
}

// An unpublished struct is not a free pass: it has to be declared a DTO, with a reason.
func TestResolveMessagesRejectsUnclassifiedDTO(t *testing.T) {
	_, err := resolveMessages(spec{bc: "dltingress"}, []discovered{{
		goType:    "transaction.ResponseEvent",
		typeName:  "ResponseEvent",
		aggregate: "transaction",
		pos:       "src/main/dltingress/domain/transaction/transaction_events.go:99",
	}})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "is never published")
}

// Every problem is reported in one run: cataloguing a bounded context with forty events should
// not take forty generations.
func TestResolveMessagesReportsEveryProblemAtOnce(t *testing.T) {
	_, err := resolveMessages(spec{bc: "dltingress"}, []discovered{
		{goType: "transaction.FirstEvent", typeName: "FirstEvent", publishers: []string{"a command handler"}},
		{goType: "transaction.SecondEvent", typeName: "SecondEvent", publishers: []string{"b command handler"}},
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "transaction.FirstEvent")
	assert.Contains(t, err.Error(), "transaction.SecondEvent")
}

// Prose for an event discovery cannot find means the struct moved and the catalog did not.
func TestResolveMessagesRejectsStaleDoc(t *testing.T) {
	s := spec{
		bc:   "dltingress",
		docs: []doc{{event: custodykey.KeyCreatedEvent{}, title: "Custody key created"}},
	}

	_, err := resolveMessages(s, nil)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "documented but discovery no longer finds it")
}

// A struct declared a DTO and then published is a contradiction, and the code wins.
func TestResolveMessagesRejectsPublishedExclusion(t *testing.T) {
	s := spec{
		bc:       "dltingress",
		excluded: []exclusion{{event: custodykey.KeyCreatedEvent{}, reason: "not really"}},
	}

	_, err := resolveMessages(s, []discovered{{
		goType:     "custodykey.KeyCreatedEvent",
		typeName:   "KeyCreatedEvent",
		aggregate:  "custodykey",
		publishers: []string{"createkey command handler"},
	}})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "excluded as a DTO but is published")
}

// Two events whose type names differ only by package would overwrite each other in
// components.messages, so the collision is reported instead.
func TestResolveMessagesRejectsCollidingNames(t *testing.T) {
	s := spec{
		bc: "dltingress",
		docs: []doc{
			{event: transaction.RetriedEvent{}},
			{event: coreRetried{}},
		},
	}

	found := []discovered{
		{goType: "transaction.RetriedEvent", typeName: "RetriedEvent", aggregate: "transaction", publishers: []string{"a"}},
		{goType: "main.coreRetried", typeName: "RetriedEvent", aggregate: "process", publishers: []string{"b"}},
	}

	_, err := resolveMessages(s, found)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "resolve to the message name")
}

// coreRetried stands in for a second RetriedEvent declared in another package; only its type
// identity matters to the collision check.
type coreRetried struct {
	event.BaseEvent
}

// Derived operations: the summaries name the producers and consumers discovery found, and an
// orphan gets no receive operation at all.
func TestBuildOperationsDerivesSummaries(t *testing.T) {
	messages := []message{
		{
			name:       "KeyCreated",
			channel:    "keyCreated",
			publishers: []string{"createkey command handler"},
			consumers:  []string{"keycreatedlistener.Listener"},
			doc:        doc{receiveNote: "That listener republishes it on the cross bus."},
		},
		{name: "Saved", channel: "saved", publishers: []string{"savefailedtransaction command handler"}},
	}

	operations := buildOperations(messages)

	assert.Equal(t, "Published by the createkey command handler.", operations["sendKeyCreated"].Summary)
	assert.Equal(t,
		"Consumed by keycreatedlistener.Listener. That listener republishes it on the cross bus.",
		operations["receiveKeyCreated"].Summary,
	)
	assert.Equal(t,
		"Published by the savefailedtransaction command handler. No bounded context currently consumes it.",
		operations["sendSaved"].Summary,
	)
	assert.NotContains(t, operations, "receiveSaved")
}

// An extension whose path does not exist would otherwise be dropped without a word.
func TestGraftRejectsUnknownPath(t *testing.T) {
	_, err := graft(nil, []string{"components"}, nil)
	assert.Error(t, err)
}
