package main

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"slices"
	"strings"
	"time"
	"unicode"

	"github.com/goccy/go-yaml"
	"github.com/mitresthen/asyncapi3"

	"github.com/google/uuid"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/event"
)

const generatedHeader = `# Generated by src/cmd/genasyncapi from the Go event structs — do not edit by hand.
# Run 'make eventSpecs' after changing an event, and commit the result.

`

// spec is one bounded context's contract: what it is called, and the prose for each of its
// events. Every spec lives in catalog.go, so the whole platform's event documentation is one file
// and no bounded context's own packages know that AsyncAPI exists.
type spec struct {
	bc          string
	title       string
	version     string
	description string
	docs        []doc
	excluded    []exclusion
}

// root is the bounded context's source tree, which is also what discovery walks.
func (s spec) root() string { return filepath.Join(srcMainDir, s.bc) }

// doc is what a human has to write about one event, and nothing more. Whether the event is
// published, from where, who consumes it, which bus it travels on and what its address is are all
// read from the code by discover.go — see resolveMessages.
type doc struct {
	// event is a zero value of the event type. It carries the payload contract, through
	// reflection, and keys this entry against discovery: a renamed struct fails to compile here,
	// and a moved one fails the gate.
	event     any
	title     string
	summary   string
	aggregate aggregate

	// name overrides the message name, which otherwise is the type name without its Event suffix.
	// Needed only when two events of the same bounded context would collide under that rule.
	name string

	// sendNote and receiveNote are appended to the derived producer/consumer sentences, for what
	// the call sites cannot say: why a listener republishes, what a status transition implies.
	sendNote    string
	receiveNote string
}

// exclusion accounts for a struct that embeds event.BaseEvent but is not a message: almost always
// a command or cross-command response DTO that inherited the name by copy-paste. Listing it is
// mandatory — that is what keeps a genuinely new event from slipping past the generator.
type exclusion struct {
	event  any
	reason string
}

// aggregate names the stream an event belongs to. Whether the stream can actually be replayed is
// a separate question, answered in docs/events/<bc>-event-sourcing.md.
type aggregate struct {
	kind    string
	idField string
	note    string
}

// message is one entry of the spec: the declared prose joined with what discovery found.
type message struct {
	doc

	name       string
	goType     string
	channel    string
	address    string
	publishers []string
	consumers  []string
	cross      bool
}

func (m message) orphan() bool { return len(m.consumers) == 0 }

func (m message) server() string {
	if m.cross {
		return crossOutbox
	}

	return internalOutbox
}

// sendSummary and receiveSummary state what the code does; the notes add what it cannot say.
func (m message) sendSummary() string {
	summary := "Published by the " + joinList(m.publishers) + "."

	if m.orphan() {
		summary += " No bounded context currently consumes it."
	}

	if m.sendNote != "" {
		summary += " " + m.sendNote
	}

	return summary
}

func (m message) receiveSummary() string {
	summary := "Consumed by " + joinList(m.consumers) + "."

	if m.receiveNote != "" {
		summary += " " + m.receiveNote
	}

	return summary
}

// resolveMessages joins the catalog with discovery, and refuses to generate anything while the
// two disagree. This is the gate: a struct that embeds event.BaseEvent and is neither documented
// nor excluded fails the build, so a new event cannot reach main without reaching the catalog —
// and prose for an event that no longer exists fails just as loudly.
func resolveMessages(s spec, found []discovered) ([]message, error) {
	documented := map[string]doc{}

	for _, entry := range s.docs {
		goType := goTypeOf(entry.event)
		if _, duplicate := documented[goType]; duplicate {
			return nil, fmt.Errorf("%s: %s is documented twice", s.bc, goType)
		}

		documented[goType] = entry
	}

	dropped := map[string]string{}

	for _, entry := range s.excluded {
		dropped[goTypeOf(entry.event)] = entry.reason
	}

	messages := make([]message, 0, len(found))

	// Problems are collected rather than returned one at a time: registering a bounded context
	// with forty events should take one run, not forty.
	var problems []string

	for _, ev := range found {
		entry, isDocumented := documented[ev.goType]
		_, isExcluded := dropped[ev.goType]

		switch {
		case isDocumented && isExcluded:
			problems = append(problems, ev.pos+": "+ev.goType+" is both documented and excluded — pick one")

		case isExcluded && ev.published():
			problems = append(problems, fmt.Sprintf(
				"%s: %s is excluded as a DTO but is published by the %s — document it instead",
				ev.pos, ev.goType, joinList(ev.publishers),
			))

		case isExcluded:
			delete(dropped, ev.goType)

		case !isDocumented:
			problems = append(problems, unclassified(ev))

		default:
			delete(documented, ev.goType)
			messages = append(messages, newMessage(s.bc, entry, ev))
		}
	}

	problems = append(problems, stale(documented, dropped)...)

	err := report(s.bc, problems)
	if err != nil {
		return nil, err
	}

	slices.SortFunc(messages, func(a, b message) int { return strings.Compare(a.name, b.name) })

	return messages, assertDistinctNames(s.bc, messages)
}

func newMessage(bc string, entry doc, ev discovered) message {
	name := entry.name
	if name == "" {
		name = strings.TrimSuffix(ev.typeName, "Event")
	}

	return message{
		doc:        entry,
		name:       name,
		goType:     ev.goType,
		channel:    lowerFirst(name),
		address:    bc + "." + ev.aggregate + "." + name,
		publishers: ev.publishers,
		consumers:  ev.consumers,
		cross:      ev.cross,
	}
}

// unclassified is the gate's message. It names the file, the line and the publisher, because the
// next thing its reader does is open that file.
func unclassified(ev discovered) string {
	if ev.published() {
		return fmt.Sprintf(
			"%s: %s is published by the %s but has no entry in catalog.go — add its title, summary"+
				" and aggregate there",
			ev.pos, ev.goType, joinList(ev.publishers),
		)
	}

	return fmt.Sprintf(
		"%s: %s embeds event.BaseEvent but is never published — publish it, or list it in the"+
			" catalog's exclusions with the reason it is not a message",
		ev.pos, ev.goType,
	)
}

// stale is the gate in reverse: prose or an exclusion for something discovery cannot find, which
// means the struct moved out of the bounded context and the catalog did not follow. A rename or a
// deletion fails to compile first, which is even better.
func stale(documented map[string]doc, dropped map[string]string) []string {
	var problems []string

	for goType := range documented {
		problems = append(problems, goType+" is documented but discovery no longer finds it")
	}

	for goType := range dropped {
		problems = append(problems, goType+" is excluded but discovery no longer finds it")
	}

	slices.Sort(problems)

	return problems
}

func report(bc string, problems []string) error {
	if len(problems) == 0 {
		return nil
	}

	slices.Sort(problems)

	return fmt.Errorf("%s:\n  - %s", bc, strings.Join(problems, "\n  - "))
}

// Message names key components.messages, so two events whose type names differ only by package
// would silently overwrite each other. The doc.name override exists for that case.
func assertDistinctNames(bc string, messages []message) error {
	seen := map[string]string{}

	for _, msg := range messages {
		if other, clash := seen[msg.name]; clash {
			return fmt.Errorf(
				"%s: %s and %s both resolve to the message name %q — set doc.name on one of them",
				bc, other, msg.goType, msg.name,
			)
		}

		seen[msg.name] = msg.goType
	}

	return nil
}

// buildMessages reflects each event into components.schemas, returning the messages that
// reference those schemas and the extensions to graft onto them.
func buildMessages(messages []message) (
	map[string]asyncapi3.Message,
	map[string]json.RawMessage,
	[]extension,
	error,
) {
	out := make(map[string]asyncapi3.Message, len(messages))
	schemas := map[string]json.RawMessage{"BaseEvent": baseEventSchema}

	var exts []extension

	for _, msg := range messages {
		payload, defs, err := asyncapi3.SchemaFromType(msg.event)
		if err != nil {
			return nil, nil, nil, err
		}

		// Distinct Go types, so nothing collides; MergeSchemas is what says so out loud when a
		// future event reuses a payload type under a second name.
		err = asyncapi3.MergeSchemas(schemas, defs)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("merging schemas of %s: %w", msg.name, err)
		}

		composed, err := withBaseEvent(payload)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("composing payload of %s: %w", msg.name, err)
		}

		out[msg.name] = asyncapi3.Message{
			Name:        msg.name,
			Title:       msg.title,
			Summary:     msg.summary,
			ContentType: "application/json",
			Payload:     composed,
		}

		exts = append(exts, extension{
			path:  []string{"components", "messages", msg.name},
			items: messageExtensions(msg),
		})
	}

	return out, schemas, exts, nil
}

func messageExtensions(msg message) yaml.MapSlice {
	// Derived, not declared: the type that was reflected cannot disagree with the type documented.
	items := yaml.MapSlice{{Key: "x-go-type", Value: msg.goType}}

	if msg.orphan() {
		items = append(items, yaml.MapItem{Key: "x-orphan", Value: true})
	}

	stream := yaml.MapSlice{
		{Key: "type", Value: msg.aggregate.kind},
		{Key: "idField", Value: msg.aggregate.idField},
	}

	if msg.aggregate.note != "" {
		stream = append(stream, yaml.MapItem{Key: "note", Value: msg.aggregate.note})
	}

	return append(items, yaml.MapItem{Key: "x-aggregate", Value: stream})
}

// Every event embeds event.BaseEvent, which lives in iob-go-core with no json tags — reflection
// therefore cannot see it, and its two fields are declared here once and composed onto every
// payload. They are also the reason a payload is not camelCase throughout: the fields this
// repository owns carry camelCase json tags, these two keep their Go names. The assignment below
// is a compile-time guard: it breaks the build if the upstream fields this schema mirrors are
// renamed or removed.
var _ = event.BaseEvent{Id: uuid.UUID{}, CreatedAt: time.Time{}}

var baseEventSchema = json.RawMessage(`{
	"type": "object",
	"required": ["Id", "CreatedAt"],
	"properties": {
		"Id": {
			"type": "string",
			"format": "uuid",
			"description": "Event identity. NOT the aggregate identity. Untagged upstream, hence PascalCase."
		},
		"CreatedAt": {
			"type": "string",
			"format": "date-time",
			"description": "When the event was recorded. Untagged upstream, hence PascalCase."
		}
	}
}`)

func withBaseEvent(payload json.RawMessage) (json.RawMessage, error) {
	composed := struct {
		AllOf []json.RawMessage `json:"allOf"`
	}{
		AllOf: []json.RawMessage{json.RawMessage(`{"$ref":"#/components/schemas/BaseEvent"}`), payload},
	}

	out, err := json.Marshal(composed)
	if err != nil {
		return nil, err
	}

	return out, nil
}

// The two outbox buses every bounded context publishes on. They are the same everywhere, so they
// are described here rather than in each entry of the catalog.
const (
	internalOutbox = "internal-outbox"
	crossOutbox    = "internal-cross-outbox"
)

func buildServers() map[string]asyncapi3.Server {
	return map[string]asyncapi3.Server{
		internalOutbox: {
			Host:     "dlt-ingress",
			Protocol: "in-process",
			Description: "Events are persisted to the event_stores table by OutboxBus within the command's " +
				"transaction, then dispatched in-process by the memory relay to registered listeners.",
		},
		crossOutbox: {
			Host:     "dlt-ingress",
			Protocol: "in-process",
			Description: "Cross-context bus. Same outbox table with is_cross = true, used for events " +
				"crossing bounded context boundaries.",
		},
	}
}

// buildChannels gives every event one channel, addressed by the logical name derived from where
// the struct lives: <bc>.<declaring package>.<event without its Event suffix>.
func buildChannels(messages []message) map[string]asyncapi3.Channel {
	channels := make(map[string]asyncapi3.Channel, len(messages))

	for _, msg := range messages {
		channels[msg.channel] = asyncapi3.Channel{
			Address: msg.address,
			Servers: []asyncapi3.RefObj{asyncapi3.Ref("#/servers/" + msg.server())},
			Messages: map[string]asyncapi3.Message{
				msg.name: {Ref: "#/components/messages/" + msg.name},
			},
		}
	}

	return channels
}

// buildOperations pairs a send with the producers found at the publish call sites, and a receive
// with the listeners registered for the event. An orphan gets no receive, because nothing does.
func buildOperations(messages []message) map[string]asyncapi3.Operation {
	operations := map[string]asyncapi3.Operation{}

	for _, msg := range messages {
		operations["send"+msg.name] = operation(asyncapi3.ActionSend, msg.channel, msg.sendSummary())

		if msg.orphan() {
			continue
		}

		operations["receive"+msg.name] = operation(asyncapi3.ActionReceive, msg.channel, msg.receiveSummary())
	}

	return operations
}

func operation(action, channelName, summary string) asyncapi3.Operation {
	return asyncapi3.Operation{
		Action:  action,
		Channel: asyncapi3.Ref("#/channels/" + channelName),
		Summary: summary,
	}
}

func goTypeOf(value any) string { return fmt.Sprintf("%T", value) }

func lowerFirst(value string) string {
	if value == "" {
		return value
	}

	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])

	return string(runes)
}

// joinList reads as prose: "a", "a and b", "a, b and c".
func joinList(values []string) string {
	switch len(values) {
	case 0:
		return "nothing"
	case 1:
		return values[0]
	default:
		return strings.Join(values[:len(values)-1], ", ") + " and " + values[len(values)-1]
	}
}
