package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"

	"github.com/goccy/go-yaml"
	"github.com/mitresthen/asyncapi3"
)

// document is an AsyncAPI document plus what the library cannot express. It models no extension
// fields on any object, so "x-" keys are grafted onto the marshalled tree; and it emits JSON,
// while the committed artifact is YAML, which is also the only place a comment can survive
// generation — hence header.
type document struct {
	header string
	doc    *asyncapi3.Document
	exts   []extension
}

// extension is the set of "x-" keys to graft onto the node at path, e.g. the path
// {"components", "messages", "KeyCreated"}. A MapSlice keeps them in declaration order.
type extension struct {
	path  []string
	items yaml.MapSlice
}

// render marshals the document to the exact bytes of the committed artifact, and validates what
// it is about to return rather than what it started from: the round trip through YAML and the
// grafted extensions are part of what ships.
func render(d *document) ([]byte, error) {
	err := d.doc.Validate()
	if err != nil {
		return nil, err
	}

	raw, err := json.Marshal(d.doc)
	if err != nil {
		return nil, fmt.Errorf("marshaling document: %w", err)
	}

	// YAML is a superset of JSON, so the library's output parses here, and UseOrderedMap keeps
	// its field order instead of re-sorting the document alphabetically.
	var tree any

	err = yaml.UnmarshalWithOptions(raw, &tree, yaml.UseOrderedMap())
	if err != nil {
		return nil, fmt.Errorf("reading back marshalled document: %w", err)
	}

	for _, ext := range d.exts {
		tree, err = graft(tree, ext.path, ext.items)
		if err != nil {
			return nil, fmt.Errorf("grafting extensions: %w", err)
		}
	}

	// Two-space indent with indented sequences is what .editorconfig asks of yaml, and literal
	// blocks keep long descriptions readable instead of one escaped line.
	body, err := yaml.MarshalWithOptions(tree,
		yaml.Indent(2),
		yaml.IndentSequence(true),
		yaml.UseLiteralStyleIfMultiline(true),
		yaml.UseSingleQuote(true),
	)
	if err != nil {
		return nil, fmt.Errorf("marshaling YAML: %w", err)
	}

	// The encoder indents blank lines inside literal blocks, which .editorconfig rejects. The
	// padding is not part of the scalar, so trimming it changes nothing but the bytes.
	out := append([]byte(d.header), trimTrailingSpace(body)...)

	shipped, err := yaml.YAMLToJSON(out)
	if err != nil {
		return nil, fmt.Errorf("reading back generated YAML: %w", err)
	}

	err = asyncapi3.ValidateBytes(shipped)
	if err != nil {
		return nil, err
	}

	return out, nil
}

func trimTrailingSpace(body []byte) []byte {
	lines := bytes.Split(body, []byte("\n"))
	for i, line := range lines {
		lines[i] = bytes.TrimRight(line, " \t")
	}

	return bytes.Join(lines, []byte("\n"))
}

// graft appends items to the mapping at path. Missing paths are an error: an extension that
// silently lands nowhere is worse than a failed generation.
func graft(node any, path []string, items yaml.MapSlice) (any, error) {
	mapping, ok := node.(yaml.MapSlice)
	if !ok {
		return nil, fmt.Errorf("expected a mapping, got %T", node)
	}

	if len(path) == 0 {
		return append(mapping, items...), nil
	}

	for i, item := range mapping {
		if item.Key != path[0] {
			continue
		}

		child, err := graft(item.Value, path[1:], items)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path[0], err)
		}

		mapping[i].Value = child

		return mapping, nil
	}

	return nil, fmt.Errorf("%s: no such key", path[0])
}

// checkStale is the drift gate. Not asyncapi3.Check, whose failure message points at a command
// this repository does not have.
func checkStale(generated []byte, path string) error {
	committed, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}

	if !bytes.Equal(committed, generated) {
		return fmt.Errorf(
			"%s is stale vs the event structs (%d committed vs %d generated bytes)"+
				" — run 'make eventSpecs' and commit the result",
			path, len(committed), len(generated),
		)
	}

	return nil
}
