// Code generated by gencrosscommandname. DO NOT EDIT.

package signandsendbatchcross

func (c *CrossCommand) CrossCommandName() string {
	return "dlt-ingress/src/main/dltingress/port/crosscommand/signandsendbatch.CrossCommand"
}
