// Code generated by gencrosscommandname. DO NOT EDIT.

package createkeycross

func (c *CrossCommand) CrossCommandName() string {
	return "dlt-ingress/src/main/dltingress/port/crosscommand/createkey.CrossCommand"
}
