// Code generated by gencommandname. DO NOT EDIT.

package transitfailedtransactiontoretried

func (c *Command) CommandName() string {
	return "dlt-ingress/src/main/dltingress/internal/app/command/transitfailedtransactiontoretried.Command"
}
