// Code generated by genrepositories. DO NOT EDIT.

package mocktxqueueslotrepo

import (
	"context"
	"dlt-ingress/src/main/dltingress/internal/domain/txqueueslot"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"gitlab.com/iobuilders/projects/eng/iob-core/iob-go-core/v4/src/main/core/api/pagination"
)

type Postgres struct {
	mock.Mock
}

func (m *Postgres) Create(ctx context.Context, entity *txqueueslot.TxQueueSlot) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *Postgres) Save(ctx context.Context, entity *txqueueslot.TxQueueSlot) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *Postgres) Delete(ctx context.Context, entity *txqueueslot.TxQueueSlot) error {
	args := m.Called(ctx, entity)
	if args.Get(0) != nil {
		return args.Error(0)
	}
	return nil
}

func (m *Postgres) FindById(ctx context.Context, id uuid.UUID) (*txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*txqueueslot.TxQueueSlot), args.Error(1)
}

// ExistById checks if the TxQueueSlot with the given id exists (Mock).
func (m *Postgres) ExistById(ctx context.Context, id uuid.UUID) (bool, error) {
	args := m.Called(ctx, id)
	return args.Bool(0), args.Error(1)
}

func (m *Postgres) FindByIdPreload(ctx context.Context, id uuid.UUID) (*txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *Postgres) FindAll(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *Postgres) FindAllWithDeleted(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *Postgres) FindAllPreload(ctx context.Context) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *Postgres) FindAllPaginated(ctx context.Context, params pagination.PaginationParams) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, params)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *Postgres) FindAllPaginatedPreload(ctx context.Context, params pagination.PaginationParams) ([]txqueueslot.TxQueueSlot, error) {
	args := m.Called(ctx, params)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]txqueueslot.TxQueueSlot), args.Error(1)
}

func (m *Postgres) CountAll(ctx context.Context) (int, error) {
	args := m.Called(ctx)
	return args.Int(0), args.Error(1)
}

var _ txqueueslot.Repository = (*Postgres)(nil)
